/* ================================================================
   CLASSROOM GAMES — Custom Content
   Edit this file to add your own sentences and words.
   
   HOW TO USE:
   - sentences: used by Grammar Auction
   - words:     used by Hangman / Wheel of Fortune (alongside built-in lists)
   
   topic format:  "S{stage}/U{unit}/L{lesson} Description"
                  e.g. "S6/U6/L1 2nd Conditional"
                  Generic topics (no stage/unit) are fine too.

   In Grammar Auction, filter by topic before starting.
   In Hangman/Wheel of Fortune, custom words appear as extra word lists.
   ================================================================ */

window.CUSTOM_CONTENT = {

  sentences: [

    // ── Generic Grammar — Passive Voice ───────────────────────
    { text: "The letter was written by the student.",          correct: true,  topic: "Passive Voice" },
    { text: "The cake was ate by the children.",               correct: false, topic: "Passive Voice" },
    { text: "English is spoken all over the world.",           correct: true,  topic: "Passive Voice" },
    { text: "The window was broke by the ball.",               correct: false, topic: "Passive Voice" },
    { text: "The report will be finished by tomorrow.",        correct: true,  topic: "Passive Voice" },
    { text: "The prize was gave to the winner.",               correct: false, topic: "Passive Voice" },
    { text: "The rules must be followed at all times.",        correct: true,  topic: "Passive Voice" },
    { text: "The homework should been done before class.",     correct: false, topic: "Passive Voice" },
    { text: "The books were returned to the library.",         correct: true,  topic: "Passive Voice" },
    { text: "The car has been drove to the garage.",           correct: false, topic: "Passive Voice" },

    // ── Generic Grammar — Present Tense ───────────────────────
    { text: "She goes to school every day.",                   correct: true,  topic: "Present Tense" },
    { text: "He don't like spicy food.",                       correct: false, topic: "Present Tense" },
    { text: "They are playing football right now.",            correct: true,  topic: "Present Tense" },
    { text: "I am agree with you.",                            correct: false, topic: "Present Tense" },
    { text: "She doesn't know the answer.",                    correct: true,  topic: "Present Tense" },
    { text: "We go always to the market on Sunday.",           correct: false, topic: "Present Tense" },
    { text: "He is having a car.",                             correct: false, topic: "Present Tense" },

    // ── Generic Grammar — Past Tense ──────────────────────────
    { text: "We went to the cinema last night.",               correct: true,  topic: "Past Tense" },
    { text: "She didn't came to class yesterday.",             correct: false, topic: "Past Tense" },
    { text: "They were playing when it started raining.",      correct: true,  topic: "Past Tense" },
    { text: "I catched the bus just in time.",                 correct: false, topic: "Past Tense" },
    { text: "He had already eaten before we arrived.",         correct: true,  topic: "Past Tense" },
    { text: "Did you went to the party?",                      correct: false, topic: "Past Tense" },
    { text: "We didn't saw him at the shop.",                  correct: false, topic: "Past Tense" },

    // ── Generic Grammar — Conditionals ────────────────────────
    { text: "If it rains, we will stay inside.",               correct: true,  topic: "Conditionals" },
    { text: "If I would have money, I will buy a car.",        correct: false, topic: "Conditionals" },
    { text: "She would travel more if she had more time.",     correct: true,  topic: "Conditionals" },
    { text: "If he studies hard, he would pass.",              correct: false, topic: "Conditionals" },
    { text: "If they had left earlier, they wouldn't have missed the bus.", correct: true,  topic: "Conditionals" },
    { text: "I would have helped if you would have asked.",    correct: false, topic: "Conditionals" },
    { text: "Unless you hurry, we will be late.",              correct: true,  topic: "Conditionals" },

    // ── Generic Grammar — Reported Speech ─────────────────────
    { text: "She said that she was tired.",                    correct: true,  topic: "Reported Speech" },
    { text: "He told me he will come tomorrow.",               correct: false, topic: "Reported Speech" },
    { text: "They asked if I had seen the film.",              correct: true,  topic: "Reported Speech" },
    { text: "She said me that she liked the food.",            correct: false, topic: "Reported Speech" },
    { text: "She asked where did I live.",                     correct: false, topic: "Reported Speech" },
    { text: "They said they had already finished.",            correct: true,  topic: "Reported Speech" },
    { text: "He told that he was feeling unwell.",             correct: false, topic: "Reported Speech" },

    // ── Generic Grammar — Articles ────────────────────────────
    { text: "She is a honest person.",                         correct: false, topic: "Articles" },
    { text: "He plays the guitar every evening.",              correct: true,  topic: "Articles" },
    { text: "I had a egg for breakfast.",                      correct: false, topic: "Articles" },
    { text: "The sun rises in the east.",                      correct: true,  topic: "Articles" },
    { text: "She gave him an useful advice.",                  correct: false, topic: "Articles" },

    // ── Generic Grammar — Comparatives ────────────────────────
    { text: "She is more taller than her sister.",             correct: false, topic: "Comparatives" },
    { text: "This is the most expensive phone in the shop.",   correct: true,  topic: "Comparatives" },
    { text: "This book is more better than that one.",         correct: false, topic: "Comparatives" },
    { text: "She is the cleverest student I know.",            correct: true,  topic: "Comparatives" },
    { text: "It was the most worst day of my life.",           correct: false, topic: "Comparatives" },

    // ── Generic Grammar — Figurative Language ─────────────────
    { text: "The classroom was a zoo — noisy and chaotic.",    correct: true,  topic: "Figurative Language" },
    { text: "Time is a thief that steals our years.",          correct: true,  topic: "Figurative Language" },
    { text: "The wind whispered secrets through the trees.",   correct: true,  topic: "Figurative Language" },
    { text: "The metaphor said the moon is like a silver coin.", correct: false, topic: "Figurative Language" },
    { text: "She simile ran as fast as a cheetah.",            correct: false, topic: "Figurative Language" },
    { text: "Life is a journey with no map.",                  correct: true,  topic: "Figurative Language" },
    { text: "The old house groaned under the weight of its memories.", correct: true, topic: "Figurative Language" },

    // ── S6/U6/L1 — Unbelievable Stories: 2nd Conditional ──────
    { text: "If Violet worked on a different ship, she would survive.",             correct: true,  topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "If the Titanic had more lifeboats, fewer people would die.",           correct: false, topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "If I were the captain, I would slow down near the icebergs.",          correct: true,  topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "If you would study, you would pass the exam.",                         correct: false, topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "If the Britannic wasn't a hospital ship, more people would have died.", correct: false, topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "She would swim to safety if she knew how to swim.",                    correct: true,  topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "If you ate rotten food, you would get sick.",                          correct: true,  topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },
    { text: "She would go to jail if she steal that car.",                          correct: false, topic: "S6/U6/L1 2nd Conditional", stage: 6, unit: 6, lesson: 1 },

    // ── S6/U6/L2 — Unbelievable Stories: 3rd Conditional ──────
    { text: "If the clergy hadn't been terrible, they wouldn't have made people angry.",           correct: true,  topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If the council hadn't constructed a stage, fewer people would have died.",            correct: true,  topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If the government had paid attention, mental health wouldn't have got worse.",        correct: true,  topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If the music hadn't been played faster, fifteen people wouldn't have died.",          correct: true,  topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If they gave St Vitus a coin, they would have stopped dancing.",                      correct: false, topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If they had banned music earlier, people wouldn't have danced until they fainted.",   correct: true,  topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If I hadn't spent all my money, I would have had enough for the ticket.",             correct: true,  topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },
    { text: "If the food wasn't disgusting, it wouldn't have made people sick.",                   correct: false, topic: "S6/U6/L2 3rd Conditional", stage: 6, unit: 6, lesson: 2 },

    // ── S6/U6/L3 — Unbelievable Stories: Mixed Conditionals ───
    { text: "If they weren't argumentative, they wouldn't have fallen out.",                      correct: true,  topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If he wasn't fit, he didn't finish the race.",                                        correct: false, topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If my grandfather hadn't won a gold medal, we wouldn't live in a big house.",         correct: true,  topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If Lorz hadn't cheated, nobody would like him.",                                      correct: false, topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If I spoke English, I would have asked for directions.",                              correct: true,  topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If they hadn't closed the bowling alley, we would go there tonight.",                 correct: true,  topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If there had been a doctor on the plane, the man wouldn't have died.",                correct: true,  topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },
    { text: "If she was taller, she might have become a model.",                                   correct: false, topic: "S6/U6/L3 Mixed Conditionals", stage: 6, unit: 6, lesson: 3 },

    // ── S6/U1/L2 — Unsolved Mysteries: Defining Relative Clauses ──
    { text: "DB Cooper is the man who hijacked a plane in 1971.",                                         correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "DB Cooper is the man which hijacked a plane in 1971.",                                       correct: false, topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The money that was found on the beach matched the ransom serial numbers.",                    correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The money who was found on the beach matched the ransom serial numbers.",                     correct: false, topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The flight attendant who served Cooper described him as calm and intelligent.",               correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The parachute which Cooper used was not steerable.",                                         correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The parachute whose Cooper used was not steerable.",                                         correct: false, topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "Seattle is the city where the plane landed to exchange the passengers.",                     correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "Seattle is the city which the plane landed to exchange the passengers.",                     correct: false, topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The FBI agent who took over the case believed Cooper did not survive.",                      correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The suspect whose brother identified him was Kenneth Christiansen.",                         correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "The briefcase that Cooper carried allegedly contained a bomb.",                              correct: true,  topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },
    { text: "McCoy is the suspect who hijacking a similar plane the following year.",                     correct: false, topic: "S6/U1/L2 Defining Relative Clauses", stage: 6, unit: 1, lesson: 2 },

    // ── S6/U1/L3 — Unsolved Mysteries: Non-Defining Relative Clauses ──
    { text: "The Broaddus family, who had just bought a new home, received a threatening letter.",        correct: true,  topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "The Broaddus family who had just bought a new home received a threatening letter.",          correct: false, topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "Michael Langford, whose family had lived there since the 1960s, was questioned by police.", correct: true,  topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "Michael Langford, who family had lived there since the 1960s, was questioned by police.",   correct: false, topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "The letter, which arrived just three days after they bought the house, was signed 'The Watcher.'", correct: true,  topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "The letter which arrived just three days after they bought the house was signed 'The Watcher.'",   correct: false, topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "Westfield, where the family had hoped to raise their children, became a place of fear.",    correct: true,  topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "Westfield, which the family had hoped to raise their children, became a place of fear.",    correct: false, topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "The second letter, that contained the children's names, arrived two weeks later.",          correct: false, topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "Netflix, which produced a drama about the case, renewed interest in 2022.",                 correct: true,  topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "Netflix, who produced a drama about the case, renewed interest in 2022.",                   correct: false, topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },
    { text: "The Watcher, whose identity remains unknown, has never been charged.",                      correct: true,  topic: "S6/U1/L3 Non-Defining Relative Clauses", stage: 6, unit: 1, lesson: 3 },

    // ── S6/U1/L3 — Unsolved Mysteries: Who / Whose / Whom ─────
    { text: "The neighbour with whom police spoke denied everything.",                                   correct: true,  topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The neighbour with who police spoke denied everything.",                                    correct: false, topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "We met a detective whose methods were unconventional.",                                     correct: true,  topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "We met a detective whom methods were unconventional.",                                      correct: false, topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The person to whom the letter was addressed felt terrified.",                               correct: true,  topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The person to who the letter was addressed felt terrified.",                                correct: false, topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The suspect from whom DNA was taken was eliminated.",                                       correct: true,  topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The suspect from who DNA was taken was eliminated.",                                        correct: false, topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "I know a woman whose house was watched for years.",                                         correct: true,  topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "I know a woman whom house was watched for years.",                                          correct: false, topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The author from whom the letter came was never identified.",                                correct: true,  topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },
    { text: "The author from which the letter came was never identified.",                               correct: false, topic: "S6/U1/L3 Who Whose Whom", stage: 6, unit: 1, lesson: 3 },

    // ── S6/U1/L4 — Unsolved Mysteries: Shortened Relative Clauses ──
    { text: "The ship carrying 1,700 barrels of alcohol was found completely abandoned.",                correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "The ship which carrying 1,700 barrels of alcohol was found completely abandoned.",          correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "The barrels made from red oak were more likely to leak naturally.",                         correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "The barrels making from red oak were more likely to leak naturally.",                       correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "The sailors working on the Dei Gratia discovered the abandoned ship.",                      correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "The sailors worked on the Dei Gratia discovered the abandoned ship.",                       correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "CO2 emitted by factories contributes to global warming.",                                  correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "CO2 emitting by factories contributes to global warming.",                                 correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "This portrait, painted by the captain's wife, was found still on board.",                  correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "This portrait, painting by the captain's wife, was found still on board.",                 correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "People working for private companies usually earn more than public sector workers.",        correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "People worked for private companies usually earn more than public sector workers.",         correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "Animals facing extinction need international protection.",                                 correct: true,  topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },
    { text: "Animals faced extinction need international protection.",                                  correct: false, topic: "S6/U1/L4 Shortened Relative Clauses", stage: 6, unit: 1, lesson: 4 },

    // ── S6/U8/L3 — Advertising: Formal vs Informal ────────────
    { text: "I am writing to complain in the strongest terms about my recent experience.",         correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "I'm writing cos I'm well annoyed about what happened on my holiday.",                 correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "I would be grateful if you could look into this matter at your earliest convenience.", correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "Can you sort this out ASAP? It's really not good enough.",                            correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "I look forward to receiving your response regarding this matter.",                    correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "Get back to me soon yeah? I wanna know what you're gonna do about it.",               correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "Furthermore, the facilities were not of the standard described in your advertisement.", correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "Also the place was well dirty and nothing like the pictures on the website.",          correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "I wish to draw your attention to a number of serious discrepancies.",                  correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "There were loads of problems and I wanna tell you about all of them.",                 correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "I would therefore request a partial refund of no less than fifty percent.",            correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "I want half my money back at least, it was a total waste of time.",                    correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "On our arrival, we were informed by your representative that the excursions had been cancelled.", correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "When we got there your rep told us all the trips were off. She didn't even say sorry.", correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "Yours faithfully is used to close a formal letter when the recipient's name is unknown.", correct: true,  topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },
    { text: "You'd write 'Yours faithfully' when you don't know who you're writing to.",            correct: false, topic: "S6/U8/L3 Formal vs Informal", stage: 6, unit: 8, lesson: 3 },

  ],

  words: [

    // ── Generic — Literary Devices ────────────────────────────
    { word: "METAPHOR",        topic: "Literary Devices" },
    { word: "SIMILE",          topic: "Literary Devices" },
    { word: "ALLITERATION",    topic: "Literary Devices" },
    { word: "ONOMATOPOEIA",    topic: "Literary Devices" },
    { word: "PERSONIFICATION", topic: "Literary Devices" },
    { word: "HYPERBOLE",       topic: "Literary Devices" },
    { word: "FORESHADOWING",   topic: "Literary Devices" },
    { word: "JUXTAPOSITION",   topic: "Literary Devices" },
    { word: "SYMBOLISM",       topic: "Literary Devices" },
    { word: "ANAPHORA",        topic: "Literary Devices" },

    // ── Generic — Grammar Terms ───────────────────────────────
    { word: "CONJUNCTION",     topic: "Grammar Terms" },
    { word: "PREPOSITION",     topic: "Grammar Terms" },
    { word: "ADJECTIVE",       topic: "Grammar Terms" },
    { word: "ADVERB",          topic: "Grammar Terms" },
    { word: "SUBORDINATE",     topic: "Grammar Terms" },
    { word: "PARTICIPLE",      topic: "Grammar Terms" },
    { word: "INFINITIVE",      topic: "Grammar Terms" },
    { word: "PASSIVE VOICE",   topic: "Grammar Terms" },

    // ── Generic — IGCSE English ───────────────────────────────
    { word: "CHARACTERISATION", topic: "IGCSE English" },
    { word: "PROTAGONIST",      topic: "IGCSE English" },
    { word: "ANTAGONIST",       topic: "IGCSE English" },
    { word: "ATMOSPHERE",       topic: "IGCSE English" },
    { word: "INFERENCE",        topic: "IGCSE English" },
    { word: "CONNOTATION",      topic: "IGCSE English" },
    { word: "NARRATIVE",        topic: "IGCSE English" },
    { word: "RHETORIC",         topic: "IGCSE English" },

    // ── Generic — Beginner ────────────────────────────────────
    { word: "APPLE",   topic: "Beginner" },
    { word: "HOUSE",   topic: "Beginner" },
    { word: "TRAIN",   topic: "Beginner" },
    { word: "WATER",   topic: "Beginner" },
    { word: "MUSIC",   topic: "Beginner" },
    { word: "SMILE",   topic: "Beginner" },
    { word: "LIGHT",   topic: "Beginner" },
    { word: "BREAD",   topic: "Beginner" },
    { word: "CHAIR",   topic: "Beginner" },
    { word: "PLANT",   topic: "Beginner" },
    { word: "SLEEP",   topic: "Beginner" },
    { word: "CLOUD",   topic: "Beginner" },
    { word: "SUGAR",   topic: "Beginner" },
    { word: "PIZZA",   topic: "Beginner" },
    { word: "BRAIN",   topic: "Beginner" },
    { word: "SNAKE",   topic: "Beginner" },
    { word: "STONE",   topic: "Beginner" },
    { word: "BERRY",   topic: "Beginner" },
    { word: "SWEET",   topic: "Beginner" },
    { word: "HORSE",   topic: "Beginner" },
    { word: "SHELL",   topic: "Beginner" },
    { word: "CYCLE",   topic: "Beginner" },
    { word: "PAPER",   topic: "Beginner" },
    { word: "RIVER",   topic: "Beginner" },
    { word: "MANGO",   topic: "Beginner" },
    { word: "BASIC",   topic: "Beginner" },
    { word: "CANDY",   topic: "Beginner" },
    { word: "SWORD",   topic: "Beginner" },
    { word: "BROOM",   topic: "Beginner" },
    { word: "SPOON",   topic: "Beginner" },
    { word: "FROG",    topic: "Beginner" },
    { word: "BEACH",   topic: "Beginner" },
    { word: "SAND",    topic: "Beginner" },
    { word: "CLOCK",   topic: "Beginner" },
    { word: "STORM",   topic: "Beginner" },
    { word: "CROWN",   topic: "Beginner" },
    { word: "PLANE",   topic: "Beginner" },
    { word: "SHEEP",   topic: "Beginner" },
    { word: "BLOOM",   topic: "Beginner" },
    { word: "LEMON",   topic: "Beginner" },
    { word: "TIGER",   topic: "Beginner" },
    { word: "BLADE",   topic: "Beginner" },
    { word: "CABLE",   topic: "Beginner" },
    { word: "SCALE",   topic: "Beginner" },
    { word: "SNAIL",   topic: "Beginner" },
    { word: "GRASS",   topic: "Beginner" },
    { word: "BRICK",   topic: "Beginner" },
    { word: "SLOPE",   topic: "Beginner" },
    { word: "WHEEL",   topic: "Beginner" },
    { word: "CUPCAKE", topic: "Beginner" },
    { word: "BANANA",  topic: "Beginner" },
    { word: "ORANGE",  topic: "Beginner" },
    { word: "BUTTON",  topic: "Beginner" },
    { word: "MARKET",  topic: "Beginner" },
    { word: "POCKET",  topic: "Beginner" },

    // ── Generic — Intermediate ────────────────────────────────
    { word: "ELEPHANT",    topic: "Intermediate" },
    { word: "NOTEBOOK",    topic: "Intermediate" },
    { word: "HOSPITAL",    topic: "Intermediate" },
    { word: "MOUNTAIN",    topic: "Intermediate" },
    { word: "TELESCOPE",   topic: "Intermediate" },
    { word: "CARNIVAL",    topic: "Intermediate" },
    { word: "SUNLIGHT",    topic: "Intermediate" },
    { word: "BACKPACK",    topic: "Intermediate" },
    { word: "TREASURE",    topic: "Intermediate" },
    { word: "VOLCANO",     topic: "Intermediate" },
    { word: "RAINFALL",    topic: "Intermediate" },
    { word: "BLUEBERRY",   topic: "Intermediate" },
    { word: "CHAMELEON",   topic: "Intermediate" },
    { word: "HARMONICA",   topic: "Intermediate" },
    { word: "CROCODILE",   topic: "Intermediate" },
    { word: "ASTEROID",    topic: "Intermediate" },
    { word: "FOOTPRINT",   topic: "Intermediate" },
    { word: "DRAGONFLY",   topic: "Intermediate" },
    { word: "SANDWICH",    topic: "Intermediate" },
    { word: "PLAYGROUND",  topic: "Intermediate" },
    { word: "WILDERNESS",  topic: "Intermediate" },
    { word: "CHOCOLATE",   topic: "Intermediate" },
    { word: "PINEAPPLE",   topic: "Intermediate" },
    { word: "HONEYCOMB",   topic: "Intermediate" },
    { word: "SNOWFLAKE",   topic: "Intermediate" },
    { word: "RAINBOW",     topic: "Intermediate" },
    { word: "BUTTERFLY",   topic: "Intermediate" },
    { word: "MARATHON",    topic: "Intermediate" },
    { word: "BILLIARDS",   topic: "Intermediate" },
    { word: "KANGAROO",    topic: "Intermediate" },
    { word: "ORCHESTRA",   topic: "Intermediate" },
    { word: "HURRICANE",   topic: "Intermediate" },
    { word: "CENTAUR",     topic: "Intermediate" },
    { word: "MYSTICAL",    topic: "Intermediate" },
    { word: "CEREMONY",    topic: "Intermediate" },
    { word: "FESTIVAL",    topic: "Intermediate" },
    { word: "TRIATHLON",   topic: "Intermediate" },
    { word: "ARCHITECT",   topic: "Intermediate" },
    { word: "BLUEPRINT",   topic: "Intermediate" },
    { word: "NARRATIVE",   topic: "Intermediate" },
    { word: "SYMMETRY",    topic: "Intermediate" },
    { word: "MOSAIC",      topic: "Intermediate" },
    { word: "PORTRAIT",    topic: "Intermediate" },
    { word: "CERAMICS",    topic: "Intermediate" },
    { word: "GLACIER",     topic: "Intermediate" },
    { word: "TUNDRA",      topic: "Intermediate" },
    { word: "MONSOON",     topic: "Intermediate" },
    { word: "CANYON",      topic: "Intermediate" },
    { word: "RAINFOREST",  topic: "Intermediate" },
    { word: "GIRAFFE",     topic: "Intermediate" },
    { word: "WOLVERINE",   topic: "Intermediate" },
    { word: "ARMADILLO",   topic: "Intermediate" },
    { word: "OSTRICH",     topic: "Intermediate" },
    { word: "TORTOISE",    topic: "Intermediate" },
    { word: "ALCHEMY",     topic: "Intermediate" },
    { word: "SPELLBOOK",   topic: "Intermediate" },
    { word: "WARLOCK",     topic: "Intermediate" },
    { word: "GRIMOIRE",    topic: "Intermediate" },
    { word: "ENCHANTER",   topic: "Intermediate" },
    { word: "RUNESTONE",   topic: "Intermediate" },
    { word: "PHOENIX",     topic: "Intermediate" },
    { word: "SANCTUARY",   topic: "Intermediate" },
    { word: "EXPEDITION",  topic: "Intermediate" },
    { word: "NAVIGATOR",   topic: "Intermediate" },
    { word: "HINTERLAND",  topic: "Intermediate" },
    { word: "ECONOMICS",   topic: "Intermediate" },
    { word: "GEOMETRY",    topic: "Intermediate" },
    { word: "STATISTICS",  topic: "Intermediate" },
    { word: "ASTRONOMY",   topic: "Intermediate" },

    // ── Generic — Advanced ────────────────────────────────────
    { word: "PHOTOSYNTHESIS",   topic: "Advanced" },
    { word: "THERMODYNAMICS",   topic: "Advanced" },
    { word: "HYPOTHESIS",       topic: "Advanced" },
    { word: "METAMORPHOSIS",    topic: "Advanced" },
    { word: "ANTHROPOLOGY",     topic: "Advanced" },
    { word: "LINGUISTICS",      topic: "Advanced" },
    { word: "PSYCHOLOGY",       topic: "Advanced" },
    { word: "NEUROSCIENCE",     topic: "Advanced" },
    { word: "MICROBIOLOGY",     topic: "Advanced" },
    { word: "ARCHIPELAGO",      topic: "Advanced" },
    { word: "PENINSULA",        topic: "Advanced" },
    { word: "EQUATORIAL",       topic: "Advanced" },
    { word: "CONSTITUTION",     topic: "Advanced" },
    { word: "REFERENDUM",       topic: "Advanced" },
    { word: "LEGISLATION",      topic: "Advanced" },
    { word: "AMBASSADOR",       topic: "Advanced" },
    { word: "DIPLOMACY",        topic: "Advanced" },
    { word: "SYMBOLISM",        topic: "Advanced" },
    { word: "FORESHADOWING",    topic: "Advanced" },
    { word: "PERSONIFICATION",  topic: "Advanced" },
    { word: "ONOMATOPOEIA",     topic: "Advanced" },
    { word: "HYPERBOLE",        topic: "Advanced" },
    { word: "PARADOXICAL",      topic: "Advanced" },
    { word: "EUPHEMISTIC",      topic: "Advanced" },
    { word: "OSCILLATION",      topic: "Advanced" },
    { word: "REFRACTION",       topic: "Advanced" },
    { word: "ACCELERATION",     topic: "Advanced" },
    { word: "ENTROPY",          topic: "Advanced" },
    { word: "QUANTUM",          topic: "Advanced" },
    { word: "MAGNIFICATION",    topic: "Advanced" },
    { word: "ILLUSTRATION",     topic: "Advanced" },
    { word: "ABSTRACTION",      topic: "Advanced" },
    { word: "CHOREOGRAPHY",     topic: "Advanced" },
    { word: "SYNTHESIZER",      topic: "Advanced" },
    { word: "COMPOSITION",      topic: "Advanced" },
    { word: "CEREMONIAL",       topic: "Advanced" },
    { word: "MYTHOLOGICAL",     topic: "Advanced" },
    { word: "TRADITIONALIST",   topic: "Advanced" },
    { word: "HEREDITARY",       topic: "Advanced" },
    { word: "PHILOSOPHICAL",    topic: "Advanced" },
    { word: "INTERPRETATION",   topic: "Advanced" },
    { word: "MISCOMMUNICATION", topic: "Advanced" },
    { word: "DISPROPORTIONATE", topic: "Advanced" },
    { word: "UNPREDICTABLE",    topic: "Advanced" },
    { word: "IRREVERSIBLE",     topic: "Advanced" },
    { word: "INCONCEIVABLE",    topic: "Advanced" },
    { word: "HALLUCINATION",    topic: "Advanced" },
    { word: "REJUVENATION",     topic: "Advanced" },
    { word: "CONFIGURATION",    topic: "Advanced" },
    { word: "INFRASTRUCTURE",   topic: "Advanced" },
    { word: "MISINTERPRET",     topic: "Advanced" },
    { word: "COUNTERMEASURE",   topic: "Advanced" },
    { word: "RECONNAISSANCE",   topic: "Advanced" },
    { word: "TRANSCENDENCE",    topic: "Advanced" },
    { word: "MULTIPLICATION",   topic: "Advanced" },
    { word: "REVOLUTIONARY",    topic: "Advanced" },
    { word: "CONSEQUENTIAL",    topic: "Advanced" },
    { word: "UNCONVENTIONAL",   topic: "Advanced" },

    // ── S6/U1/L1 — Unsolved Mysteries: Phoenix Lights ───────────
    { word: "CLUSTER",         topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "ALLEGEDLY",       topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "ORBS",            topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "GRAINY",          topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "HOVERING",        topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "EYEWITNESS",      topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "TESTIMONY",       topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "DISTORTION",      topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "ASTONISHING",     topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "RADAR",           topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "ILLUMINATED",     topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "RECOLLECTION",    topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "PURSUED",         topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "CONFOUNDING",     topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "ALTITUDE",        topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "UNACKNOWLEDGED",  topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },
    { word: "PRESS CONFERENCE",topic: "S6/U1/L1 Phoenix Lights", stage: 6, unit: 1, lesson: 1 },

    // ── S6/U1/L1 — Unsolved Mysteries: Men in Black ───────────
    { word: "EVIDENCE",        topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },
    { word: "RADIOACTIVITY",   topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },
    { word: "SURVEILLING",     topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },
    { word: "THEORIZE",        topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },
    { word: "ELIMINATED",      topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },
    { word: "INVESTIGATOR",    topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },
    { word: "EXPEDITION",      topic: "S6/U1/L1 Men in Black", stage: 6, unit: 1, lesson: 1 },

    // ── S6/U1/L2 — Unsolved Mysteries: DB Cooper ──────────────
    { word: "BOURBON",         topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "STEWARDESS",      topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "RANSOM",          topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "PARACHUTE",       topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "HIJACKING",       topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "SERIAL NUMBERS",  topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "EXCHANGED",       topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },
    { word: "SCOURED",         topic: "S6/U1/L2 DB Cooper", stage: 6, unit: 1, lesson: 2 },

    // ── S6/U1/L3 — Unsolved Mysteries: The Watcher ────────────
    { word: "SURVEILLING",     topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "EVIDENCE",        topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "PROSECUTORS",     topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "CONCOCTING",      topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "ANONYMOUS",       topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "PLIGHT",          topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "AMBIVALENCE",     topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "PSYCHOLOGICAL",   topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "TRAUMA",          topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "INCAPABLE",       topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },
    { word: "VOUCHED",         topic: "S6/U1/L3 The Watcher", stage: 6, unit: 1, lesson: 3 },

    // ── S6/U1/L4 — Unsolved Mysteries: Mary Celeste ───────────
    { word: "INAUSPICIOUS",    topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "ARCHIPELAGO",     topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "FOUL PLAY",       topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "MUTINOUS",        topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "ACCUMULATED",     topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "SEISMICALLY",     topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "FORESHOCK",       topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "SEEPAGE",         topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "DISARRAY",        topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "POSITED",         topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "SALVAGE",         topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },
    { word: "SEAWORTHY",       topic: "S6/U1/L4 Mary Celeste", stage: 6, unit: 1, lesson: 4 },

    // ── S6/U7/L1 — CLIL: Space ────────────────────────────────
    { word: "ORBIT",         topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "EXOPLANET",     topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "GRAVITY",       topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "NEBULA",        topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "SUPERNOVA",     topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "GALAXY",        topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "LIGHT-YEAR",    topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "BLACK HOLE",    topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },
    { word: "ASTEROID BELT", topic: "S6/U7/L1 Space",     stage: 6, unit: 7, lesson: 1 },

    // ── S6/U7/L2 — CLIL: Geography ───────────────────────────
    { word: "ARCHIPELAGO",   topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "PENINSULA",     topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "PLATEAU",       topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "DELTA",         topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "ATOLL",         topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "TUNDRA",        topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "SAVANNA",       topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "VOLCANO",       topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "FJORD",         topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "OASIS",         topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "CANYON",        topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },
    { word: "BASIN",         topic: "S6/U7/L2 Geography", stage: 6, unit: 7, lesson: 2 },

    // ── S6/U7/L3 — CLIL: History ──────────────────────────────
    { word: "PHILOSOPHER",          topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "CIVIL WAR",            topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "MEDIEVAL ERA",         topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "MONARCH",              topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "COLONISATION",         topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "DICTATOR",             topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "RENAISSANCE",          topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "REFORMER",             topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "REVOLUTION",           topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "INDUSTRIAL REVOLUTION",topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },
    { word: "EMPIRE",               topic: "S6/U7/L3 History", stage: 6, unit: 7, lesson: 3 },

    // ── S6/U7/L4 — CLIL: Chemistry ───────────────────────────
    { word: "BEAKER",            topic: "S6/U7/L4 Chemistry", stage: 6, unit: 7, lesson: 4 },
    { word: "TEST TUBE",         topic: "S6/U7/L4 Chemistry", stage: 6, unit: 7, lesson: 4 },
    { word: "BUNSEN BURNER",     topic: "S6/U7/L4 Chemistry", stage: 6, unit: 7, lesson: 4 },
    { word: "GRADUATED CYLINDER",topic: "S6/U7/L4 Chemistry", stage: 6, unit: 7, lesson: 4 },
    { word: "PIPETTE",           topic: "S6/U7/L4 Chemistry", stage: 6, unit: 7, lesson: 4 },
    { word: "FLASK",             topic: "S6/U7/L4 Chemistry", stage: 6, unit: 7, lesson: 4 },

    // ── S6/U2/L1 — At the Movies: Ellipsis ──────────────────
    { text: "Laurie agreed to invent the camera although he didn't want to.",                              correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Laurie agreed to invent the camera although he didn't want to invent it.",                    correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Maria is going to try to get the film I want but I'm sure she won't be able to.",             correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Maria is going to try to get the film I want but I'm sure she won't be able to get the film.",correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "I didn't ask after Pam's mother when I should have.",                                         correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "I didn't ask after Pam's mother when I should have asked after her.",                         correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Laurel's always upsetting his friend although he doesn't mean to.",                           correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Laurel's always upsetting his friend although he doesn't mean to upset him.",                 correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "My brother didn't go to the cinema last night although he could have.",                        correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "My brother didn't go to the cinema last night although he could have gone to the cinema.",     correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Buster doesn't know if he'll be able to make the jump, but he certainly hopes to.",           correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Buster doesn't know if he'll be able to make the jump, but he certainly hopes to make the jump.", correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Leland breeds horses now, but he didn't used to.",                                            correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "Leland breeds horses now, but he didn't used to breed horses.",                               correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "When Liam asked Grace to go out for a drink, she said she'd love to.",                        correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "When Liam asked Grace to go out for a drink, she said she'd love to go out for a drink.",     correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "He wants me to go to the cinema with him and I would like to.",                               correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "He wants me to go to the cinema with him and I would like to go to the cinema with him.",     correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "You don't have to tell me if you don't want.",                                                correct: false, topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },
    { text: "You don't have to tell me if you don't want to.",                                             correct: true,  topic: "S6/U2/L1 Ellipsis", stage: 6, unit: 2, lesson: 1 },

    // ── S6/U2/L2 — At the Movies: Reported Speech 1 ──────────
    { text: "The Terminator said that he would be back.",                                                  correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The Terminator said that he will be back.",                                                   correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The Godfather said he was going to make him an offer he couldn't refuse.",                    correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The Godfather said he is going to make him an offer he can't refuse.",                        correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Dorothy said she had a feeling they weren't in Kansas anymore.",                               correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Dorothy said she has a feeling they aren't in Kansas anymore.",                                correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Jack shouted that he was the king of the world.",                                             correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Jack shouted that he is the king of the world.",                                              correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Brody said we were going to need a bigger boat.",                                             correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Brody said you are going to need a bigger boat.",                                             correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The reporter said it wasn't the aeroplanes — it was Beauty that had killed the Beast.",       correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The reporter said it wasn't the aeroplanes — it was Beauty that killed the Beast.",           correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The Wicked Witch said she would get them and their little dog too.",                          correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "The Wicked Witch said she will get you and your little dog too.",                             correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "William said that they might take their lives, but they would never take their freedom.",     correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "William said that they may take their lives, but they will never take their freedom.",        correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Forrest said that life was like a box of chocolates.",                                        correct: true,  topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },
    { text: "Forrest told that life was like a box of chocolates.",                                        correct: false, topic: "S6/U2/L2 Reported Speech 1", stage: 6, unit: 2, lesson: 2 },

    // ── S6/U2/L3 — At the Movies: Reported Speech 2 ──────────
    { text: "Mr Johnson threatened to call a member of staff if they didn't stop talking.",               correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Mr Johnson promised to call a member of staff if they didn't stop talking.",                 correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Jo begged them not to drop all of the popcorn.",                                             correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Jo warned them not to drop all of the popcorn.",                                             correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Ben recommended us to go and see Batman.",                                                   correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Ben insisted on us going to see Batman.",                                                    correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Sue congratulated them on winning the Oscar trophy.",                                        correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Sue recommended them on winning the Oscar trophy.",                                          correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Steve promised to come with us to the cinema.",                                              correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Steve claimed to come with us to the cinema.",                                               correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Tom warned us not to watch the new Annabelle movie.",                                        correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Tom begged us not to watch the new Annabelle movie.",                                        correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Her dad insisted on her finishing her vegetables.",                                           correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "Her dad insisted her to finish her vegetables.",                                              correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "He claimed never to have watched that movie.",                                                correct: true,  topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },
    { text: "He promised never to have watched that movie.",                                               correct: false, topic: "S6/U2/L3 Reported Speech 2", stage: 6, unit: 2, lesson: 3 },

    // ── S6/U2/L1 — At the Movies: Early Years Vocab ─────────
    { word: "ILLUSIONIST",     topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "LINEAR",          topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "INFLUENTIAL",     topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "ADAPTED",         topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "REEL",            topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "DISTRIBUTION",    topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "NARRATIVE",       topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "DOMINANT",        topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "PERMANENT",       topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "SUPERSPECTACLE",  topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "LEGITIMATE",      topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "UNCONVENTIONAL",  topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "TEMPERATE",       topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "TOPOGRAPHY",      topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },
    { word: "PLENTIFUL",       topic: "S6/U2/L1 Early Years", stage: 6, unit: 2, lesson: 1 },

    // ── S6/U2/L2 — At the Movies: Colour & Sound Vocab ───────
    { word: "COMMISSIONED",    topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "SYNCHRONIZED",    topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "MAINSTREAM",      topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "SCORES",          topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "AMPLIFICATION",   topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "MAGNIFIED",       topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "NOVELTY",         topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "SOPHISTICATED",   topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "REBUFFED",        topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "MARKETABILITY",   topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "ACCOMPANIMENT",   topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "ENTHUSIASTIC",    topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },
    { word: "CONVERSION",      topic: "S6/U2/L2 Colour & Sound", stage: 6, unit: 2, lesson: 2 },

    // ── S6/U2/L3-L4 — At the Movies: Modern Era Vocab ────────
    { word: "AUTOMATED",       topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "DEVOTED",         topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "VIDEOCASSETTE",   topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "INDEPENDENT",     topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "COMMERCIAL",      topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "FRANCHISE",       topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "TECHNIQUES",      topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "ANIMATRONICS",    topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "UTILISE",         topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "INTEGRAL",        topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },
    { word: "CULTURAL",        topic: "S6/U2/L3 Modern Era", stage: 6, unit: 2, lesson: 3 },

    // ── S6/U6 — Unbelievable Stories: Vocabulary ─────────────
    { word: "HULL",            topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "STERN",           topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "BOW",             topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "DECK",            topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "ANCHOR",          topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "RUDDER",          topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "PROPELLER",       topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "LIFEBOAT",        topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "ICEBERG",         topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "PLAGUE",          topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "CURSE",           topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "MARATHON",        topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "PODIUM",          topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "SPECTACLE",       topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "COMMITTEE",       topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "BOUNTY",          topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "HARVEST",         topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "VETERAN",         topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "BULKHEAD",        topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "TRANSATLANTIC",   topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "SIMULTANEOUSLY",  topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "DEHYDRATION",     topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "DEVASTATION",     topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "IMPENDING",       topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "PASTORAL",        topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "HOARDING",        topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "HYPERBOLE",       topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "INVULNERABILITY", topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "EXAGGERATED",     topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "SARCASTICALLY",   topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "UNDISPUTED",      topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "SKIRMISH",        topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "OPTIMISTICALLY",  topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "COMPREHENDING",   topic: "S6/U6 Vocab", stage: 6, unit: 6 },
    { word: "HAEMORRHAGING",   topic: "S6/U6 Vocab", stage: 6, unit: 6 },

  ]

};
