// questions.js — Classroom Games Question Packs
// Used by: Connect 4, Blockbusters (future)
//
// FORMAT:
//   question   : string
//   answer     : string
//   distractors: array of 3 strings
//   topic      : string — shown in filter UI; prefix with initials if multi-teacher e.g. "SR — Past Passive"
//   stage      : integer (optional — omit for unlinked/personal packs)
//   unit       : integer (optional)
//   lesson     : integer (optional)
//
// Multiple selections are merged into one shuffled pool.
// Unlinked questions (no stage/unit/lesson) appear under "— Personal / Unlinked —"

window.QUESTIONS = [

  // ════════════════════════════════════════════════════════════════
  // S5 / U1 — Gangsters
  // ════════════════════════════════════════════════════════════════

  // ── Gangsters — Comprehension (L1–L4 general) ────────────────────────────
  { question: "What was Al Capone's nickname?", answer: "Scarface", distractors: ["Blackjack", "The Fixer", "Big Al"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What illegal business made Capone rich during Prohibition?", answer: "Bootlegging — selling illegal alcohol", distractors: ["Drug smuggling", "Kidnapping for ransom", "Gambling"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What was Al Capone eventually convicted of?", answer: "Tax evasion", distractors: ["Murder", "Bootlegging", "Bribery"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "Which event turned public opinion against Capone?", answer: "The Saint Valentine's Day Massacre", distractors: ["The Chicago Fire", "The Wall Street Crash", "His arrest for tax evasion"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What period was Prohibition in the USA?", answer: "1920 to 1933", distractors: ["1910 to 1920", "1925 to 1945", "1930 to 1940"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "Who was the most successful pirate of all time?", answer: "Madame Zheng", distractors: ["Blackbeard", "Henry Morgan", "Barbarossa"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "How many ships did Madame Zheng command at her peak?", answer: "1,800", distractors: ["10", "200", "500"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "How did Madame Zheng's pirate career end?", answer: "She negotiated her own amnesty and retired peacefully", distractors: ["She was captured and executed", "She was killed in battle", "She fled to another country"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What is Robin Hood famous for?", answer: "Stealing from the rich and giving to the poor", distractors: ["Defeating the French army", "Overthrowing King Richard", "Building Sherwood Castle"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "Was Robin Hood definitely a real person?", answer: "No — he is a legend and his existence is debated", distractors: ["Yes — records confirm he lived in 1160", "Yes — he fought in the Crusades", "No — he was invented in the 1800s"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What was Pablo Escobar's nickname?", answer: "The King of Cocaine", distractors: ["El Jefe", "The Shadow", "Public Enemy No.1"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What was unusual about the prison Escobar was sent to?", answer: "He had it built to his own specifications and chose his own guards", distractors: ["It was on a remote island", "He shared it with rival cartel leaders", "It was the most secure prison in Colombia"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What was Bugsy Siegel's contribution to Las Vegas?", answer: "He financed and developed the Flamingo Hotel casino", distractors: ["He built the Bellagio", "He legalised gambling in Nevada", "He founded the city of Las Vegas"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "Was Bugsy Siegel convicted of murder?", answer: "No — he was acquitted in 1942", distractors: ["Yes — he served 5 years", "Yes — sentenced to death", "No — the case never went to court"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "Which gangster was once elected to parliament?", answer: "Pablo Escobar", distractors: ["Al Capone", "Bugsy Siegel", "Madame Zheng"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "How did Capone stay safe from law enforcement?", answer: "He bribed the mayor and police officers", distractors: ["He wore disguises", "He fled to another city", "He hired private bodyguards"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "What did Capone, Escobar and Robin Hood have in common?", answer: "All were seen as Robin Hood figures who gave money to the poor", distractors: ["All were eventually acquitted", "All escaped from prison", "All lived in the same era"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },
  { question: "How did Bugsy Siegel die?", answer: "He was shot dead at his girlfriend's home in Beverly Hills", distractors: ["He died in prison", "He was executed by the state", "He died of illness after release"], topic: "Gangsters — Comprehension", stage: 5, unit: 1 },

  // ── Past Passive — Beginner ───────────────────────────────────────────────
  { question: "Complete: 'The telephone ___ by Alexander Graham Bell.'", answer: "was invented", distractors: ["invented", "is invented", "were invented"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Complete: 'Capone ___ in New York in 1899.'", answer: "was born", distractors: ["born", "is born", "were born"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Past passive is formed using...", answer: "was / were + past participle", distractors: ["will + verb", "has / have + past participle", "is / are + verb"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Which sentence is past passive?", answer: "The money was stolen from the bank.", distractors: ["The robbers stole the money.", "They are stealing the money.", "Someone has stolen the money."], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Change to passive: 'Bank robbers stole $50m.'", answer: "$50m was stolen by bank robbers.", distractors: ["$50m were stolen by bank robbers.", "Bank robbers were stolen $50m.", "$50m is stolen by bank robbers."], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Which uses 'were' correctly in the past passive?", answer: "Seven rivals were murdered in broad daylight.", distractors: ["Seven rivals was murdered.", "Seven rival were murdered.", "Seven rivals is murdered."], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Past participle of 'build'?", answer: "built", distractors: ["builded", "building", "builds"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Past participle of 'write'?", answer: "written", distractors: ["wrote", "writed", "writing"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Past participle of 'send'?", answer: "sent", distractors: ["sended", "send", "sending"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },
  { question: "Past participle of 'steal'?", answer: "stolen", distractors: ["stealed", "stole", "stealing"], topic: "Past Passive — Beginner", stage: 5, unit: 1, lesson: 3 },

  // ── Past Passive — Intermediate ───────────────────────────────────────────
  { question: "The passive is used when the doer is UNKNOWN. Which example shows this?", answer: "My camera was stolen from my hotel room.", distractors: ["Capone bribed the police.", "She opened a gambling house.", "He moved to Chicago."], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "The passive is used when the doer is IMPLIED. Which example shows this?", answer: "Capone was born in New York City in 1899.", distractors: ["A million dollars was stolen.", "The house was built in 2016.", "The soldiers were sent to fight."], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "The passive is used when the doer is UNIMPORTANT. Which example shows this?", answer: "The confederation was dismantled in April 1810.", distractors: ["Capone was born in 1899.", "My bike was stolen.", "He was acquitted by the jury."], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "Change to passive: 'The cleaner cleaned the room yesterday.'", answer: "The room was cleaned yesterday.", distractors: ["The room cleaned yesterday.", "The room is cleaned yesterday.", "Yesterday the cleaner was cleaned."], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "Change to passive: 'Some people broke the window last night.'", answer: "The window was broken last night.", distractors: ["The window were broken last night.", "Some people were broken the window.", "The window is broken last night."], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "How do we add the doer to a passive sentence?", answer: "Add 'by' followed by the person's name at the end", distractors: ["Add 'from' before the verb", "Move the doer to the middle", "Use 'with' after the verb"], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "Change to a passive QUESTION: 'When did they invent the television?'", answer: "When was the television invented?", distractors: ["When the television was invented?", "When is the television invented?", "When did the television invented?"], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },
  { question: "Change to passive: 'Builders built that school 20 years ago.'", answer: "That school was built 20 years ago.", distractors: ["That school were built 20 years ago.", "Builders were built that school.", "That school has been built 20 years ago."], topic: "Past Passive — Intermediate", stage: 5, unit: 1, lesson: 4 },

  // ════════════════════════════════════════════════════════════════
  // S5 / U2 — Infinitives and -ing
  // ════════════════════════════════════════════════════════════════

  // ── Verb Patterns — Which form? (-ing or infinitive) ─────────────────────
  { question: "Which is correct?", answer: "I enjoy swimming in the sea.", distractors: ["I enjoy to swim in the sea.", "I enjoy swim in the sea.", "I enjoyed to swimming in the sea."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "She decided to study medicine.", distractors: ["She decided studying medicine.", "She decided study medicine.", "She decides studying medicine."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "He hopes to go to university next year.", distractors: ["He hopes going to university next year.", "He hope to going university.", "He is hoping going to university."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "They want to visit their grandmother.", distractors: ["They want visiting their grandmother.", "They want visit their grandmother.", "They wanting to visit their grandmother."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "I fancy going for a walk.", distractors: ["I fancy to go for a walk.", "I fancy go for a walk.", "I fancied to going for a walk."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "We can't afford to go to the cinema very often.", distractors: ["We can't afford going to the cinema very often.", "We can't afford go to the cinema.", "We couldn't afford going to the cinema very often."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "I suggested having dinner early.", distractors: ["I suggested to have dinner early.", "I suggested have dinner early.", "I suggest having to dinner early."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "She agreed to meet Linda at four o'clock.", distractors: ["She agreed meeting Linda at four o'clock.", "She agreed meet Linda at four o'clock.", "She agrees to meeting Linda."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "I don't mind waiting.", distractors: ["I don't mind to wait.", "I don't mind wait.", "I minded to waiting."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "He refused to answer any more questions.", distractors: ["He refused answering any more questions.", "He refused answer any more questions.", "He refuses to answering any more questions."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "I don't want to go out tonight. I'm very tired.", distractors: ["I don't want going out tonight.", "I don't want go out tonight.", "I wasn't wanting to go out tonight."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "They avoided crossing that old bridge.", distractors: ["They avoided to cross that old bridge.", "They avoided cross that old bridge.", "They avoid to crossing that old bridge."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "He managed to contact his cousins in Australia.", distractors: ["He managed contacting his cousins in Australia.", "He managed contact his cousins.", "He manages to contacting his cousins."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "I finished writing my essay and then played computer games.", distractors: ["I finished to write my essay.", "I finish writing my essay.", "I had finished to write my essay."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },
  { question: "Which is correct?", answer: "She admitted taking my camera.", distractors: ["She admitted to take my camera.", "She admitted take my camera.", "She admits to taking my camera."], topic: "Verb Patterns — Which Form?", stage: 5, unit: 2, lesson: 1 },

  // ── Verb Patterns — Which category? ──────────────────────────────────────
  { question: "Is 'enjoy' followed by -ing or to + infinitive?", answer: "-ing only (e.g. I enjoy swimming)", distractors: ["to + infinitive only", "Either -ing or to, same meaning", "Neither — it takes a noun only"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'hope' followed by -ing or to + infinitive?", answer: "to + infinitive only (e.g. I hope to pass)", distractors: ["-ing only", "Either -ing or to, same meaning", "Either, with a change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'suggest' followed by -ing or to + infinitive?", answer: "-ing only (e.g. I suggest leaving early)", distractors: ["to + infinitive only", "Either -ing or to, same meaning", "Either, with a change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'promise' followed by -ing or to + infinitive?", answer: "to + infinitive only (e.g. I promise to call)", distractors: ["-ing only", "Either -ing or to, same meaning", "Either, with a change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'risk' followed by -ing or to + infinitive?", answer: "-ing only (e.g. Don't risk missing the train)", distractors: ["to + infinitive only", "Either -ing or to, same meaning", "Either, with a change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'like' followed by -ing or to + infinitive?", answer: "Either -ing or to, with very similar meaning", distractors: ["-ing only", "to + infinitive only", "Either, with a big change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'love' followed by -ing or to + infinitive?", answer: "Either -ing or to, with very similar meaning", distractors: ["-ing only", "to + infinitive only", "Either, with a big change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },
  { question: "Is 'deny' followed by -ing or to + infinitive?", answer: "-ing only (e.g. He denied stealing the money)", distractors: ["to + infinitive only", "Either -ing or to, same meaning", "Either, with a change in meaning"], topic: "Verb Patterns — Categories", stage: 5, unit: 2, lesson: 1 },

  // ── Stop / Remember / Forget / Try — Meaning Change ──────────────────────
  { question: "'I stopped smoking.' What does this mean?", answer: "I gave up the habit of smoking — I no longer smoke.", distractors: ["I paused what I was doing in order to smoke.", "I tried to smoke but couldn't.", "I forgot that I had been smoking."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I stopped to smoke.' What does this mean?", answer: "I paused what I was doing in order to have a cigarette.", distractors: ["I gave up the habit of smoking.", "I tried to smoke but failed.", "I remembered to smoke at the right time."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I remembered to call my uncle.' What does this mean?", answer: "I didn't forget — I made the call as planned.", distractors: ["I have a memory of calling my uncle in the past.", "I tried calling my uncle but he didn't answer.", "I stopped what I was doing to call my uncle."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I remember calling my uncle.' What does this mean?", answer: "I have a memory of making that call — it happened in the past.", distractors: ["I didn't forget to make the call.", "I tried to call but couldn't.", "I stopped what I was doing in order to call."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I forgot to visit the Empire State Building.' What does this mean?", answer: "I had planned to visit but it slipped my mind — I didn't go.", distractors: ["I have no memory of visiting it.", "I tried to visit but it was closed.", "I stopped myself from visiting it."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I'll never forget visiting the Empire State Building.' What does this mean?", answer: "I went there and it was so memorable I'll always remember it.", distractors: ["I planned to go but forgot.", "I tried to go but couldn't.", "I've never been there."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I tried to stand up, but I couldn't.' What does this mean?", answer: "I made an attempt to stand but was unable to.", distractors: ["I experimented with standing up to see what would happen.", "I stopped standing up deliberately.", "I remember standing up at some point."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },
  { question: "'I tried standing up, but I still couldn't see.' What does this mean?", answer: "I experimented with standing up to see if it would help — it didn't.", distractors: ["I attempted to stand but was physically unable to.", "I remembered to stand up.", "I stopped standing up."], topic: "Stop, Remember, Forget, Try", stage: 5, unit: 2, lesson: 3 },

  // ── Advanced Verb Patterns — Verb + Object ────────────────────────────────
  { question: "What structure is: 'They wanted her to go to university'?", answer: "verb + object + to infinitive", distractors: ["verb + -ing", "verb + object + -ing", "verb + to infinitive"], topic: "Advanced Verb Patterns", stage: 5, unit: 2, lesson: 3 },
  { question: "What structure is: 'The principal made me wait outside'?", answer: "verb + object + infinitive WITHOUT to", distractors: ["verb + object + to infinitive", "verb + -ing", "verb + object + past participle"], topic: "Advanced Verb Patterns", stage: 5, unit: 2, lesson: 3 },
  { question: "What structure is: 'Let's get your bike repaired'?", answer: "verb + object + past participle", distractors: ["verb + object + to infinitive", "verb + -ing", "verb + object + infinitive without to"], topic: "Advanced Verb Patterns", stage: 5, unit: 2, lesson: 3 },
  { question: "Which sentence is correct?", answer: "She let me borrow her phone.", distractors: ["She let me to borrow her phone.", "She let me borrowing her phone.", "She let me borrowed her phone."], topic: "Advanced Verb Patterns", stage: 5, unit: 2, lesson: 3 },
  { question: "Which sentence is correct?", answer: "He got his car repaired at the garage.", distractors: ["He got his car to repair at the garage.", "He got his car repairing at the garage.", "He got to repair his car at the garage."], topic: "Advanced Verb Patterns", stage: 5, unit: 2, lesson: 3 },

  // ── Active and Passive ────────────────────────────────────────────────────
  { question: "Which sentence is in the passive voice?", answer: "Apple was founded by Steve Jobs and Steve Wozniak.", distractors: ["Steve Jobs founded Apple in 1976.", "Steve Jobs helped design the first Macintosh.", "Jobs left Apple in 1985 after a dispute."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Change to passive: 'Larry Page and Sergey Brin created Google in 1996.'", answer: "Google was created by Larry Page and Sergey Brin in 1996.", distractors: ["Google is created by Larry Page and Sergey Brin.", "Google were created by Larry Page and Sergey Brin.", "Google created by Larry Page and Sergey Brin in 1996."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Change to passive: 'They made the first storage unit from Lego bricks.'", answer: "The first storage unit was made from Lego bricks.", distractors: ["The first storage unit is made from Lego bricks.", "Lego bricks were made from the first storage unit.", "The first storage unit made from Lego bricks."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Change to passive: 'Jonathan Ives designed the iMac.'", answer: "The iMac was designed by Jonathan Ives.", distractors: ["The iMac is designed by Jonathan Ives.", "The iMac were designed by Jonathan Ives.", "Jonathan Ives was designed the iMac."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Why do we use the passive voice in 'Our car window was smashed last night'?", answer: "We don't know who smashed it — the doer is unknown.", distractors: ["We want to focus on the person who did it.", "The active form is grammatically wrong here.", "It sounds more polite than the active form."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Why might a writer choose passive in 'Apple was founded in 1976' rather than active?", answer: "To focus on Apple, not on the people who founded it.", distractors: ["The active voice is not possible here.", "The passive always sounds more formal.", "There is no real difference — either is equally good."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "'They offered Harry a job.' Which passive is preferred?", answer: "Harry was offered a job.", distractors: ["A job was offered to Harry.", "Harry offered a job.", "A job was offered by Harry."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "'My uncle gave me a phone for Christmas.' Rewrite in the passive.", answer: "I was given a phone for Christmas by my uncle.", distractors: ["A phone was given to me by my uncle for Christmas.", "I was give a phone for Christmas.", "Me was given a phone for Christmas."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Why do verbs like give, offer, send and show often use the person as the passive subject?", answer: "Because the person (indirect object) is usually more important than the thing.", distractors: ["Because the active form doesn't exist for these verbs.", "Because English grammar requires it.", "Because the thing (direct object) is always unknown."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },
  { question: "Change to passive: 'Someone sent me a really funny video clip.'", answer: "I was sent a really funny video clip.", distractors: ["A really funny video clip was sent to me.", "I was sended a really funny video clip.", "Me was sent a really funny video clip."], topic: "Active and Passive", stage: 5, unit: 2, lesson: 4 },

  // ── S5/U2 Comprehension (Sean / Alan / Apple) ─────────────────────────────
  { question: "What is the capital city of Ireland?", answer: "Dublin", distractors: ["Cork", "Belfast", "Galway"], topic: "Infinitives & -ing — Comprehension", stage: 5, unit: 2 },
  { question: "What sport is unique to Ireland and not played anywhere else?", answer: "Gaelic football and hurling", distractors: ["Rugby and golf", "Soccer and cricket", "Tennis and horse racing"], topic: "Infinitives & -ing — Comprehension", stage: 5, unit: 2 },
  { question: "Which Irish band does Sean mention in his letter?", answer: "U2", distractors: ["Coldplay", "Westlife only", "Thin Lizzy only"], topic: "Infinitives & -ing — Comprehension", stage: 5, unit: 2 },
  { question: "What does Alan from Edinburgh say he feels like doing instead of studying?", answer: "Playing video games all day", distractors: ["Hanging out with friends", "Watching films", "Going to the gym"], topic: "Infinitives & -ing — Comprehension", stage: 5, unit: 2 },
  { question: "How much did Steve Jobs earn as CEO of Apple per year?", answer: "$1 a year", distractors: ["$1 million a year", "$1 billion a year", "Nothing — he worked for free"], topic: "Infinitives & -ing — Comprehension", stage: 5, unit: 2 },
  { question: "What was the first Google storage unit made from?", answer: "Lego bricks", distractors: ["Cardboard boxes", "Recycled hard drives", "Wooden shelves"], topic: "Infinitives & -ing — Comprehension", stage: 5, unit: 2 },

  // ── Have Something Done ───────────────────────────────────────────────────
  { question: "What does 'I had my hair cut' mean?", answer: "Someone else cut my hair — I arranged and paid for it", distractors: ["I cut my own hair", "My hair was cut by accident", "I am going to cut my hair soon"], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },
  { question: "What is the structure of 'have something done'?", answer: "have + object + past participle", distractors: ["have + past participle + object", "have + object + infinitive", "be + object + past participle"], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },
  { question: "Which sentence uses 'have something done' correctly?", answer: "I had my car serviced last week.", distractors: ["I had serviced my car last week.", "My car had serviced last week.", "I have service my car last week."], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },
  { question: "Escobar 'had his own prison built.' Who actually did the building?", answer: "Construction workers — Escobar organised and paid for it", distractors: ["Escobar built it himself", "The Colombian government built it", "His guards built it voluntarily"], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },
  { question: "Complete: 'Lisa didn't repair the roof herself. She ___'", answer: "had the roof repaired.", distractors: ["repaired the roof.", "was repairing the roof.", "has the roof repair."], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },
  { question: "Which tense is: 'I am having my hair cut'?", answer: "Present continuous", distractors: ["Past simple", "Present perfect", "Future simple"], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },
  { question: "Complete: 'I didn't fix my bicycle. I ___'", answer: "had my bicycle fixed.", distractors: ["fixed my bicycle.", "had fixed my bicycle.", "was having my bicycle fix."], topic: "Have Something Done", stage: 5, unit: 1, lesson: 4 },

  // ════════════════════════════════════════════════════════════════
  // S5 / U3 — Conditionals
  // ════════════════════════════════════════════════════════════════

  // ── First Conditional ─────────────────────────────────────────
  { question: "What is the first conditional used for?", answer: "A real possibility in the present or future", distractors: ["An imaginary situation in the past", "An unreal situation in the present", "A habitual action in the past"], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "What tenses do we use in the first conditional?", answer: "Present simple in the if clause + will + infinitive in the main clause", distractors: ["Past simple in the if clause + would + infinitive in the main clause", "Past perfect in the if clause + would have + past participle", "Present simple in both clauses"], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which sentence is a correct first conditional?", answer: "If you study hard, you will pass your exam.", distractors: ["If you studied hard, you will pass your exam.", "If you study hard, you would pass your exam.", "If you will study hard, you will pass your exam."], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "When do we use a comma in a conditional sentence?", answer: "When the if clause comes first", distractors: ["When the main clause comes first", "Always, regardless of word order", "Never — conditional sentences don't use commas"], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "What is the difference between 'will' and 'might' in a first conditional?", answer: "'Will' shows certainty; 'might' shows the outcome is less certain", distractors: ["'Will' is past tense; 'might' is present tense", "They mean exactly the same thing", "'Might' is more formal than 'will'"], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which is correct?", answer: "If Adam buys a lottery ticket, he might win.", distractors: ["If Adam will buy a lottery ticket, he might win.", "If Adam bought a lottery ticket, he might win.", "If Adam buys a lottery ticket, he would win."], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which is correct?", answer: "If the teacher is sick, we won't get any homework.", distractors: ["If the teacher will be sick, we won't get any homework.", "If the teacher was sick, we won't get any homework.", "If the teacher is sick, we wouldn't get any homework."], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which version correctly moves the if clause to the end?", answer: "You will be tired tomorrow if you go to bed too late.", distractors: ["You will be tired tomorrow if you will go to bed too late.", "You would be tired tomorrow if you go to bed too late.", "You will be tired tomorrow, if you go to bed too late."], topic: "First Conditional", stage: 5, unit: 3, lesson: 1 },

  // ── Second Conditional ────────────────────────────────────────
  { question: "What is the second conditional used for?", answer: "An imaginary or unreal situation in the present or future", distractors: ["A real possibility in the present or future", "An unreal situation in the past", "A habitual action in the present"], topic: "Second Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "What tenses do we use in the second conditional?", answer: "Past simple in the if clause + would + infinitive in the main clause", distractors: ["Present simple in the if clause + will + infinitive in the main clause", "Past perfect in the if clause + would have + past participle", "Present simple in the if clause + would + infinitive"], topic: "Second Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which sentence is a correct second conditional?", answer: "If I lived in Spain, I would fight a bull.", distractors: ["If I live in Spain, I would fight a bull.", "If I lived in Spain, I will fight a bull.", "If I had lived in Spain, I would fight a bull."], topic: "Second Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "What is the difference? 'If I live in Japan, I will eat sushi.' vs 'If I lived in Japan, I would eat sushi.'", answer: "The first is a real possibility; the second is imaginary — the speaker doesn't expect it to happen", distractors: ["The first is about the past; the second is about the future", "The first is more formal; the second is informal", "There is no difference in meaning"], topic: "Second Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which sentence uses the second conditional to give advice?", answer: "If I were you, I would buy a lottery ticket.", distractors: ["If I am you, I will buy a lottery ticket.", "If I had been you, I would have bought a lottery ticket.", "If I were you, I will buy a lottery ticket."], topic: "Second Conditional", stage: 5, unit: 3, lesson: 1 },
  { question: "Which is correct?", answer: "If William won the lottery, he would buy a red Ferrari.", distractors: ["If William wins the lottery, he would buy a red Ferrari.", "If William won the lottery, he will buy a red Ferrari.", "If William had won the lottery, he would buy a red Ferrari."], topic: "Second Conditional", stage: 5, unit: 3, lesson: 2 },
  { question: "Which is correct?", answer: "If she were older, they would let her into the club.", distractors: ["If she was older, they will let her into the club.", "If she is older, they would let her into the club.", "If she had been older, they would let her into the club."], topic: "Second Conditional", stage: 5, unit: 3, lesson: 2 },

  // ── Third Conditional ─────────────────────────────────────────
  { question: "What is the third conditional used for?", answer: "An unreal or imaginary situation in the past", distractors: ["A real possibility in the present or future", "An imaginary situation in the present", "A habitual action in the past"], topic: "Third Conditional", stage: 5, unit: 3, lesson: 2 },
  { question: "What tenses do we use in the third conditional?", answer: "Had + past participle in the if clause + would have + past participle in the main clause", distractors: ["Past simple in the if clause + would + infinitive in the main clause", "Present simple in the if clause + will + infinitive in the main clause", "Past perfect in the if clause + would + infinitive in the main clause"], topic: "Third Conditional", stage: 5, unit: 3, lesson: 2 },
  { question: "Which sentence is a correct third conditional?", answer: "If there hadn't been a power cut, William wouldn't have woken up late.", distractors: ["If there wasn't a power cut, William wouldn't have woken up late.", "If there hadn't been a power cut, William wouldn't wake up late.", "If there hadn't been a power cut, William didn't wake up late."], topic: "Third Conditional", stage: 5, unit: 3, lesson: 2 },
  { question: "Which sentence is a correct third conditional?", answer: "If I had run faster, I would have caught the bus.", distractors: ["If I ran faster, I would have caught the bus.", "If I had run faster, I would catch the bus.", "If I have run faster, I would have caught the bus."], topic: "Third Conditional", stage: 5, unit: 3, lesson: 2 },
  { question: "William missed the train. Which third conditional is correct?", answer: "If the service in the café hadn't been so slow, he would have caught the train.", distractors: ["If the service in the café wasn't so slow, he would have caught the train.", "If the service in the café hadn't been so slow, he would catch the train.", "If the service in the café had been slow, he wouldn't have caught the train."], topic: "Third Conditional", stage: 5, unit: 3, lesson: 2 },
  { question: "The third conditional is often used to express what?", answer: "Regret about a past action or imagining a different outcome in the past", distractors: ["A plan for the future", "A habitual action in the past", "A real possibility in the present"], topic: "Third Conditional", stage: 5, unit: 3, lesson: 2 },

  // ── Should / Needn't Have ─────────────────────────────────────
  { question: "We use 'shouldn't have' to express what?", answer: "Disapproval of a past action — it was the wrong thing to do", distractors: ["An unnecessary past action", "Regret about something that didn't happen", "Permission to do something in the past"], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },
  { question: "We use 'needn't have' to express what?", answer: "An action that happened but was unnecessary", distractors: ["Disapproval of a past action", "Regret about something that didn't happen", "An action that was impossible in the past"], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },
  { question: "Which sentence expresses disapproval of a past action?", answer: "She shouldn't have shouted at him — it wasn't his fault.", distractors: ["She needn't have shouted at him.", "She should have shouted at him.", "She couldn't have shouted at him."], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },
  { question: "Which sentence means an action was unnecessary?", answer: "You needn't have queued for tickets — I booked them online.", distractors: ["You shouldn't have queued for tickets.", "You should have queued for tickets.", "You couldn't have queued for tickets."], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },
  { question: "David is annoyed Jenny didn't warn him. Which word fits: 'You ___ have warned me!'?", answer: "should", distractors: ["needn't", "couldn't", "might"], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },
  { question: "Jenny means David worried about nothing. Which word fits: 'You ___ have been so worried!'?", answer: "needn't", distractors: ["shouldn't", "couldn't", "should"], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },
  { question: "Which structure do we use with should/needn't have?", answer: "should/needn't + have + past participle", distractors: ["should/needn't + have + infinitive", "should/needn't + past simple", "should/needn't + be + past participle"], topic: "Should/Needn't Have", stage: 5, unit: 3, lesson: 3 },

  // ── Mixed Conditionals ────────────────────────────────────────
  { question: "What are mixed conditionals?", answer: "Sentences that mix past and present time references across the two clauses", distractors: ["Sentences that mix first and second conditionals", "Sentences that use both will and would", "Sentences that express both regret and hope"], topic: "Mixed Conditionals", stage: 5, unit: 3, lesson: 4 },
  { question: "In a Type A mixed conditional (past if clause), what goes in the main clause?", answer: "Would + base form (present result)", distractors: ["Would have + past participle", "Will + infinitive", "Had + past participle"], topic: "Mixed Conditionals", stage: 5, unit: 3, lesson: 4 },
  { question: "In a Type B mixed conditional (present if clause), what goes in the main clause?", answer: "Would have + past participle (past result)", distractors: ["Would + base form", "Will + infinitive", "Had + past participle"], topic: "Mixed Conditionals", stage: 5, unit: 3, lesson: 4 },
  { question: "Which is a correct Type A mixed conditional (past → present result)?", answer: "If I had worked harder at school, I would be rich now.", distractors: ["If I had worked harder at school, I would have been rich.", "If I worked harder at school, I would be rich now.", "If I had worked harder at school, I will be rich now."], topic: "Mixed Conditionals", stage: 5, unit: 3, lesson: 4 },
  { question: "Which is a correct Type B mixed conditional (present → past result)?", answer: "If she were taller, she would have joined the basketball team.", distractors: ["If she had been taller, she would have joined the basketball team.", "If she were taller, she would join the basketball team.", "If she is taller, she would have joined the basketball team."], topic: "Mixed Conditionals", stage: 5, unit: 3, lesson: 4 },
  { question: "In mixed conditionals, 'could' replaces what?", answer: "Would be able to (would + can)", distractors: ["Was able to in the past", "Might possibly", "Should have"], topic: "Mixed Conditionals", stage: 5, unit: 3, lesson: 4 },

  // ── I Wish ────────────────────────────────────────────────────
  { question: "What structure do we use with 'I wish' to express an unreal present?", answer: "I wish + past simple", distractors: ["I wish + present simple", "I wish + will + infinitive", "I wish + past perfect"], topic: "I Wish", stage: 5, unit: 3, lesson: 4 },
  { question: "What structure do we use with 'I wish' to express regret about the past?", answer: "I wish + past perfect (had + past participle)", distractors: ["I wish + past simple", "I wish + would + infinitive", "I wish + present perfect"], topic: "I Wish", stage: 5, unit: 3, lesson: 4 },
  { question: "Which sentence uses 'I wish' correctly to show an unreal present?", answer: "I wish I lived in Paris.", distractors: ["I wish I live in Paris.", "I wish I had lived in Paris.", "I wish I will live in Paris."], topic: "I Wish", stage: 5, unit: 3, lesson: 4 },
  { question: "Which sentence uses 'I wish' correctly to show a past regret?", answer: "I wish I hadn't spent all my money.", distractors: ["I wish I didn't spend all my money.", "I wish I don't spend all my money.", "I wish I wouldn't spend all my money."], topic: "I Wish", stage: 5, unit: 3, lesson: 4 },
  { question: "'I wish I were taller' — what does this express?", answer: "An unreal present — the speaker is not tall and wishes they were", distractors: ["A past regret — the speaker used to be taller", "A real possibility — the speaker might grow taller", "A third conditional — something didn't happen in the past"], topic: "I Wish", stage: 5, unit: 3, lesson: 4 },
  { question: "How is 'I wish + past simple' similar to the second conditional?", answer: "Both use the past simple to express an unreal or imaginary present situation", distractors: ["Both express regret about the past", "Both use would in the main clause", "Both require a comma between the two clauses"], topic: "I Wish", stage: 5, unit: 3, lesson: 4 },

  // ── Unreal Present (I'd rather / It's time / Suppose) ─────────
  { question: "Ava says 'I'd sooner we left it until after our exams.' What does this mean?", answer: "She would prefer to wait until after the exams", distractors: ["She is certain they will leave after the exams", "She is giving a first conditional prediction", "She regrets not waiting until after the exams"], topic: "Unreal Present", stage: 5, unit: 3, lesson: 4 },
  { question: "Which sentence correctly uses 'I'd rather'?", answer: "I'd rather they didn't have all those mirrors in the gym.", distractors: ["I'd rather they don't have all those mirrors in the gym.", "I'd rather they hadn't have all those mirrors in the gym.", "I'd rather they won't have all those mirrors in the gym."], topic: "Unreal Present", stage: 5, unit: 3, lesson: 4 },
  { question: "Which phrases are commonly used with the unreal present?", answer: "It's high time / I'd rather / I'd sooner / Suppose / Imagine", distractors: ["If only / Although / Nevertheless / However", "As long as / Unless / Provided that / In case", "On condition that / Even if / Whether or not"], topic: "Unreal Present", stage: 5, unit: 3, lesson: 4 },

  // ── S5/U3 Comprehension ───────────────────────────────────────
  { question: "In 'Adam and the Ferrari', why didn't Adam win the lottery despite praying every night?", answer: "He never bought a lottery ticket", distractors: ["He forgot to pray on the right night", "God was testing his patience", "William bought all the tickets"], topic: "Conditionals — Comprehension", stage: 5, unit: 3 },
  { question: "What is the moral of the fable 'Adam and the Ferrari'?", answer: "You have to take action — wishing alone is not enough", distractors: ["Money doesn't bring happiness", "Jealousy is a sin", "God answers all prayers eventually"], topic: "Conditionals — Comprehension", stage: 5, unit: 3 },
  { question: "What caused William Bobbins to wake up late?", answer: "A power cut stopped his alarm clock from ringing", distractors: ["He forgot to set his alarm", "His neighbour made too much noise", "He was ill and couldn't get up"], topic: "Conditionals — Comprehension", stage: 5, unit: 3 },
  { question: "What happened when William jumped into the shower in a panic?", answer: "He forgot to take off his pyjamas first", distractors: ["He slipped and hurt himself", "There was no hot water", "He left the taps running when he left"], topic: "Conditionals — Comprehension", stage: 5, unit: 3 },
  { question: "How was the Spanish baby swap finally discovered?", answer: "A court ordered a DNA test during a childcare dispute in 2017", distractors: ["The hospital contacted the family directly", "A routine medical check revealed the error", "The woman noticed she looked nothing like her parents"], topic: "Conditionals — Comprehension", stage: 5, unit: 3 },
  { question: "Where is the new leisure centre that Alice tells Ava about?", answer: "Jalan Damansara", distractors: ["Jalan Bukit Bintang", "Jalan Ampang", "Jalan Klang Lama"], topic: "Conditionals — Comprehension", stage: 5, unit: 3 },

  // ════════════════════════════════════════════════════════════════
  // S5 / U4 — The Hero's Journey
  // ════════════════════════════════════════════════════════════════

  // ── The Monomyth ─────────────────────────────────────────────
  { question: "What is a 'monomyth'?", answer: "A universal story template also known as the hero's journey", distractors: ["A story told in verse form", "A myth involving only one character", "A story with no villain"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "What is a narrative archetype?", answer: "A common story template or pattern found across many different stories", distractors: ["A character who appears in many different books", "A type of poem used in ancient literature", "A story written in the first person"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "What are the three essential stages of the hero's journey?", answer: "Departure, Initiation, Return", distractors: ["Beginning, Climax, Ending", "Ordinary World, Special World, Home", "Call, Quest, Victory"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "In the Departure stage, what happens?", answer: "The hero leaves the familiar world behind", distractors: ["The hero defeats the villain", "The hero learns a lesson and is transformed", "The hero meets their mentor for the first time"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "In the Initiation stage, what happens?", answer: "The hero learns to navigate the unfamiliar world and faces the main obstacle", distractors: ["The hero returns home transformed", "The hero refuses the call to adventure", "The hero is introduced living in the ordinary world"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "In the Return stage, what happens?", answer: "The hero returns to the familiar world, transformed by the experience", distractors: ["The hero leaves home for the first time", "The hero meets the villain for the first time", "The hero refuses to go on the journey"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "How many steps are there in the full monomyth?", answer: "17", distractors: ["3", "7", "12"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },
  { question: "The classical version of the hero's journey was known as an 'epic'. Which ancient epic is mentioned as an example?", answer: "Homer's Odyssey", distractors: ["Virgil's Aeneid", "Dante's Inferno", "Chaucer's Canterbury Tales"], topic: "The Monomyth", stage: 5, unit: 4, lesson: 1 },

  // ── 7 Steps of the Hero's Journey ────────────────────────────
  { question: "What is 'the ordinary world' in the hero's journey?", answer: "The familiar setting where the hero lives before the adventure begins", distractors: ["The magical world the hero travels to", "The place where the hero defeats the villain", "The place the hero returns to at the end"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },
  { question: "What is 'the call to adventure'?", answer: "The event or message that invites the hero to leave their ordinary world", distractors: ["The moment the hero defeats the villain", "The moment the hero meets their love interest", "The moment the hero returns home"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },
  { question: "What is the 'refusal of the call'?", answer: "The hero's initial hesitation or reluctance to follow the call to adventure", distractors: ["The villain refusing to fight the hero", "The mentor refusing to help the hero", "The hero refusing to return home at the end"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },
  { question: "What role does the mentor play in the hero's journey?", answer: "They give the hero counsel and convince them to follow the call to adventure", distractors: ["They are the main obstacle the hero must overcome", "They betray the hero near the end of the story", "They provide the elixir or prize for the hero"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },
  { question: "What is 'crossing the threshold'?", answer: "The moment the hero commits to the adventure and leaves the ordinary world", distractors: ["The moment the hero defeats the villain", "The moment the hero first refuses the call", "The moment the hero returns home"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },
  { question: "What is 'the ordeal' in the hero's journey?", answer: "The main challenge or battle where the hero faces the greatest obstacle", distractors: ["The hero's refusal to leave home", "The mentor convincing the hero to go", "The hero's return to the ordinary world"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },
  { question: "What might the hero receive after overcoming the ordeal?", answer: "A physical token, a love interest, or wisdom — sometimes all three", distractors: ["A new mentor to replace the old one", "A map showing the way back home", "An invitation to fight the villain again"], topic: "7 Steps", stage: 5, unit: 4, lesson: 1 },

  // ── Star Wars ─────────────────────────────────────────────────
  { question: "What is Luke Skywalker's 'ordinary world' in Star Wars?", answer: "Living with his aunt and uncle on a farm on Tatooine", distractors: ["Fighting with the Rebel Alliance against the Empire", "Training to become a Jedi with Obi-Wan Kenobi", "Rescuing Princess Leia from the Death Star"], topic: "Hero's Journey — Star Wars", stage: 5, unit: 4, lesson: 1 },
  { question: "What is Luke's 'call to adventure' in Star Wars?", answer: "R2-D2 plays him a distress message from Princess Leia", distractors: ["Obi-Wan gives him his father's lightsabre", "The Death Star destroys Alderaan", "He discovers he can use the Force"], topic: "Hero's Journey — Star Wars", stage: 5, unit: 4, lesson: 1 },
  { question: "Who is Luke Skywalker's mentor in Star Wars?", answer: "Obi-Wan Kenobi", distractors: ["Han Solo", "Princess Leia", "R2-D2"], topic: "Hero's Journey — Star Wars", stage: 5, unit: 4, lesson: 1 },
  { question: "What convinces Luke to follow the call in Star Wars?", answer: "Obi-Wan shows him his father's lightsabre", distractors: ["Han Solo offers him money", "R2-D2 refuses to play the message again", "Princess Leia contacts him directly"], topic: "Hero's Journey — Star Wars", stage: 5, unit: 4, lesson: 1 },
  { question: "What is Luke's 'ordeal' in Star Wars?", answer: "Rescuing Princess Leia and using the Force to destroy the Death Star", distractors: ["Leaving Tatooine with Obi-Wan and Han Solo", "Receiving his father's lightsabre from Obi-Wan", "Deciding to become a Jedi and join the Rebels"], topic: "Hero's Journey — Star Wars", stage: 5, unit: 4, lesson: 1 },

  // ── The Matrix ────────────────────────────────────────────────
  { question: "What is Neo's 'ordinary world' in The Matrix?", answer: "He is a bored computer programmer by day and a hacker called Neo by night", distractors: ["He is a soldier fighting against the machines", "He is a teacher training others to fight inside the Matrix", "He is a rebel leader planning to free humanity"], topic: "Hero's Journey — The Matrix", stage: 5, unit: 4, lesson: 1 },
  { question: "What is Neo's 'call to adventure' in The Matrix?", answer: "He receives a message saying everything is not as it seems and is told to 'follow the white rabbit'", distractors: ["Morpheus gives him the red and blue pill choice", "Agent Smith tries to capture him", "Trinity tells him the machines are real"], topic: "Hero's Journey — The Matrix", stage: 5, unit: 4, lesson: 1 },
  { question: "Who is Neo's mentor in The Matrix?", answer: "Morpheus", distractors: ["Trinity", "Agent Smith", "The Oracle"], topic: "Hero's Journey — The Matrix", stage: 5, unit: 4, lesson: 1 },
  { question: "What represents 'crossing the threshold' in The Matrix?", answer: "Neo chooses the red pill and is shown what the Matrix really is", distractors: ["Neo defeats Agent Smith inside the Matrix", "Neo receives a message telling him to follow the white rabbit", "Neo allows himself to be captured by the agents"], topic: "Hero's Journey — The Matrix", stage: 5, unit: 4, lesson: 1 },

  // ── Harry Potter ──────────────────────────────────────────────
  { question: "What is Harry Potter's 'ordinary world' at the start of the story?", answer: "He lives with his aunt and uncle, sleeping in the cupboard under the stairs", distractors: ["He lives at Hogwarts in Gryffindor tower", "He lives with Hagrid in a hut on the edge of Hogwarts", "He lives in Diagon Alley above the Leaky Cauldron"], topic: "Hero's Journey — Harry Potter", stage: 5, unit: 4, lesson: 1 },
  { question: "What is Harry's 'call to adventure'?", answer: "He receives a letter from Hogwarts inviting him to attend", distractors: ["Dumbledore appears at his house and explains the truth", "He discovers his parents' wands in a locked cupboard", "He is told by his aunt and uncle that he is a wizard"], topic: "Hero's Journey — Harry Potter", stage: 5, unit: 4, lesson: 1 },
  { question: "Who is Harry Potter's first mentor in the Philosopher's Stone?", answer: "Hagrid", distractors: ["Albus Dumbledore", "Professor McGonagall", "Ron Weasley"], topic: "Hero's Journey — Harry Potter", stage: 5, unit: 4, lesson: 1 },
  { question: "What represents Harry 'crossing the threshold' in the Philosopher's Stone?", answer: "He crosses platform 9¾ at King's Cross, leaving the normal world for the magical one", distractors: ["He defeats Voldemort at the end of the first book", "Hagrid tells him he is a wizard and brings him to Diagon Alley", "He receives his letter from Hogwarts for the first time"], topic: "Hero's Journey — Harry Potter", stage: 5, unit: 4, lesson: 1 },

  // ── Lord of the Rings ─────────────────────────────────────────
  { question: "What is Frodo's 'ordinary world' at the start of Lord of the Rings?", answer: "He lives in the Shire, enjoying a peaceful life with his friends", distractors: ["He lives in Rivendell with the elves", "He lives in Gondor training to be a warrior", "He lives with Gandalf in a tower in Orthanc"], topic: "Hero's Journey — Lord of the Rings", stage: 5, unit: 4, lesson: 1 },
  { question: "What is Frodo's 'call to adventure' in Lord of the Rings?", answer: "Gandalf discovers the ring of power and asks Frodo to undertake a journey with it", distractors: ["The Nazgûl attack the Shire and Frodo must flee", "Bilbo gives Frodo the ring and disappears at a party", "Sam convinces Frodo to leave the Shire and see the world"], topic: "Hero's Journey — Lord of the Rings", stage: 5, unit: 4, lesson: 1 },
  { question: "Who is Frodo's mentor in Lord of the Rings?", answer: "Gandalf", distractors: ["Aragorn", "Samwise Gamgee", "Legolas"], topic: "Hero's Journey — Lord of the Rings", stage: 5, unit: 4, lesson: 1 },
  { question: "What does Gandalf tell Frodo to convince him to go?", answer: "That he has a pure heart and is the one who must bear the burden of the ring", distractors: ["That the ring will give him great power if he uses it wisely", "That the Shire will be destroyed if he stays", "That Bilbo needs his help to complete the original quest"], topic: "Hero's Journey — Lord of the Rings", stage: 5, unit: 4, lesson: 1 },

  // ── Character Development ─────────────────────────────────────
  { question: "Why do writers start the hero in a vulnerable or difficult situation?", answer: "It creates sympathy and gives the character room to grow and develop", distractors: ["It makes the story shorter and easier to write", "It ensures the villain is more powerful than the hero", "It allows the hero to skip the refusal of the call stage"], topic: "Character Development", stage: 5, unit: 4, lesson: 2 },
  { question: "What does 'show don't tell' mean in writing?", answer: "Reveal character and situation through actions and details rather than stating them directly", distractors: ["Use dialogue instead of description whenever possible", "Write in the first person so the reader sees everything", "Avoid using adjectives and adverbs in your writing"], topic: "Character Development", stage: 5, unit: 4, lesson: 2 },
  { question: "What is a character's 'motivation'?", answer: "The reason why the character does what they do in the story", distractors: ["The character's physical appearance and clothing", "The relationship between the hero and the villain", "The genre or type of story being told"], topic: "Character Development", stage: 5, unit: 4, lesson: 2 },
  { question: "Why did Bruce Wayne become Batman?", answer: "His parents were murdered in front of him when he was a child", distractors: ["He wanted to become the most powerful person in Gotham", "He was bitten by a radioactive bat as a child", "He discovered a secret cave beneath his family's mansion"], topic: "Character Development", stage: 5, unit: 4, lesson: 2 },
  { question: "Why does Roald Dahl describe Charlie Bucket's poverty in such detail?", answer: "To make the reader sympathise with Charlie and want him to have a better life", distractors: ["To explain why Charlie doesn't go to school", "To show that the story is set in Victorian England", "To contrast with the richness of Willy Wonka's factory"], topic: "Character Development", stage: 5, unit: 4, lesson: 2 },
  { question: "A character who starts the story vulnerable and ends it transformed is a feature of what?", answer: "The hero's journey — the adventure changes the hero as a person", distractors: ["A non-linear narrative where events are told out of order", "A first-person narrative where the hero tells their own story", "A story with a twist ending that surprises the reader"], topic: "Character Development", stage: 5, unit: 4, lesson: 2 },

  // ── Villains & Supporting Characters ─────────────────────────
  { question: "What is an antagonist?", answer: "The villain or opposing force who conflicts with the hero's goals", distractors: ["A character who supports the hero throughout the story", "The narrator who tells the story from outside", "A character who appears briefly and then disappears"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },
  { question: "What is a 'conflicting motivation' in the context of villains?", answer: "The villain wants something that directly opposes what the hero wants", distractors: ["The villain changes their mind about their goal mid-story", "The villain has no clear reason for their actions", "The villain and hero share the same goal but disagree on method"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },
  { question: "Who is Harry Potter's villain?", answer: "Voldemort", distractors: ["Draco Malfoy", "Professor Snape", "Dudley Dursley"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },
  { question: "Who is Batman's villain?", answer: "The Joker", distractors: ["The Penguin", "Two-Face", "Bane"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },
  { question: "Who is Luke Skywalker's villain?", answer: "Darth Vader", distractors: ["Emperor Palpatine", "Grand Moff Tarkin", "Jabba the Hutt"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },
  { question: "How can supporting characters help develop the hero's personality?", answer: "By being opposite to the hero — highlighting the hero's traits through contrast", distractors: ["By always agreeing with the hero and supporting their decisions", "By being more powerful than the hero so the hero must work harder", "By narrating the story from their own point of view"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },
  { question: "The villain is described as 'the opposite side of the coin' from the hero. What does this mean?", answer: "The villain's goals and values mirror but directly oppose the hero's", distractors: ["The villain is physically identical to the hero", "The villain started life as a hero before turning evil", "The villain is always defeated because the hero is more powerful"], topic: "Villains and Supporting Characters", stage: 5, unit: 4, lesson: 3 },

  // ── Planning & Genre ──────────────────────────────────────────
  { question: "What is the genre of a story?", answer: "The type or category of story it is", distractors: ["The theme or moral lesson of the story", "The style in which the story is written", "The number of characters in the story"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "Which of these best describes a fantasy story?", answer: "Often inspired by myths and folklore, featuring magic and supernatural creatures", distractors: ["Based on imagined future scientific discoveries or technology", "Features danger and excitement outside the character's everyday life", "A story based on real historical events with fictional characters"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "Which of these best describes a science fiction story?", answer: "Based on imagined future scientific or technological advancements, often involving space or time travel", distractors: ["Inspired by real-world myths and folklore with magical creatures", "Features a hero who travels to an unusual place and must get back home", "A story about a character who discovers a hidden talent"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "Which of these best describes an adventure story?", answer: "Features danger and excitement with events outside the character's everyday life", distractors: ["Based on imagined future scientific discoveries", "Inspired by myths and folklore with supernatural creatures", "A story told from multiple points of view"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "What is a storyboard used for?", answer: "To plan the different stages of a story visually, showing what happens at each point", distractors: ["To write out the full dialogue of a story before writing it", "To list all the vocabulary words that will be used in the story", "To decide which genre the story belongs to"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "What is the purpose of planning a story before writing it?", answer: "It keeps ideas focused, helps the narrative flow, and prevents the writer from getting stuck", distractors: ["It ensures the story is exactly 600 words long", "It decides the genre automatically based on your characters", "It replaces the need for a first draft"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "Which is a popular theme in children's fiction according to Lesson 4?", answer: "Courage, friendship, belonging, family, growing up, anger", distractors: ["War, politics, economics, technology, science, religion", "Romance, betrayal, revenge, power, greed, corruption", "Satire, parody, irony, absurdism, surrealism, postmodernism"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },

  // ── Writing Craft ─────────────────────────────────────────────
  { question: "Why should the ordeal be the longest part of your hero's journey story?", answer: "It is the climax — the main challenge the hero faces, requiring the most development", distractors: ["Because the beginning and end are always the same length", "Because the ordeal is the only part that needs adjectives and adverbs", "Because it is the only part of the story with dialogue"], topic: "Writing Craft", stage: 5, unit: 4, lesson: 5 },
  { question: "Which writing tip is given for the progress test?", answer: "Use lots of adjectives and adverbs to make the writing vivid", distractors: ["Write entirely in the present tense to create tension", "Avoid using dialogue so the story keeps moving", "Use short sentences throughout to maintain pace"], topic: "Writing Craft", stage: 5, unit: 4, lesson: 5 },
  { question: "What is the difference between an adjective and an adverb?", answer: "An adjective describes a noun; an adverb describes a verb, adjective, or other adverb", distractors: ["An adjective comes after the verb; an adverb comes before the noun", "An adjective describes an action; an adverb describes a thing", "There is no difference — they are both types of describing words"], topic: "Writing Craft", stage: 5, unit: 4, lesson: 5 },
  { question: "Frozen is given as an example of which genre?", answer: "Fantasy", distractors: ["Science fiction", "Adventure", "Historical fiction"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },
  { question: "Alice's Adventures in Wonderland is given as an example of which genre?", answer: "Fantasy", distractors: ["Science fiction", "Adventure", "Historical fiction"], topic: "Planning and Genre", stage: 5, unit: 4, lesson: 4 },

];