// VOCAB — Let's Go Level 1 Flashcards
// img paths: img/letsgol1/<filename>.jpg

const VOCAB = [

  // Unit 1
  { word: "PENCIL", hint: "a pencil", emoji: "🖼", img: "../../img/letsgol1/u1_001_a-pencil.jpg", action: "🖼", answer: "It is an a pencil.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PEN", hint: "a pen", emoji: "🖼", img: "../../img/letsgol1/u1_002_a-pen.jpg", action: "🖼", answer: "It is an a pen.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BAG", hint: "a bag", emoji: "🖼", img: "../../img/letsgol1/u1_003_a-bag.jpg", action: "🖼", answer: "It is an a bag.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BOOK", hint: "a book", emoji: "🖼", img: "../../img/letsgol1/u1_004_a-book.jpg", action: "🖼", answer: "It is an a book.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DESK", hint: "a desk", emoji: "🖼", img: "../../img/letsgol1/u1_005_a-desk.jpg", action: "🖼", answer: "It is an a desk.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CHAIR", hint: "a chair", emoji: "🖼", img: "../../img/letsgol1/u1_006_a-chair.jpg", action: "🖼", answer: "It is an a chair.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "RULER", hint: "a ruler", emoji: "🖼", img: "../../img/letsgol1/u1_007_a-ruler.jpg", action: "🖼", answer: "It is an a ruler.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "ERASER", hint: "an eraser", emoji: "🖼", img: "../../img/letsgol1/u1_008_an-eraser.jpg", action: "🖼", answer: "It is an an eraser.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "MAP", hint: "a map", emoji: "🖼", img: "../../img/letsgol1/u1_009_a-map.jpg", action: "🖼", answer: "It is an a map.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "MARKER", hint: "a marker", emoji: "🖼", img: "../../img/letsgol1/u1_010_a-marker.jpg", action: "🖼", answer: "It is an a marker.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "GLOBE", hint: "a globe", emoji: "🖼", img: "../../img/letsgol1/u1_011_a-globe.jpg", action: "🖼", answer: "It is an a globe.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TABLE", hint: "a table", emoji: "🖼", img: "../../img/letsgol1/u1_012_a-table.jpg", action: "🖼", answer: "It is an a table.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BOARD", hint: "a board", emoji: "🖼", img: "../../img/letsgol1/u1_013_a-board.jpg", action: "🖼", answer: "It is an a board.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "WASTEBASKET", hint: "a wastebasket", emoji: "🖼", img: "../../img/letsgol1/u1_014_a-wastebasket.jpg", action: "🖼", answer: "It is an a wastebasket.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "POSTER", hint: "a poster", emoji: "🖼", img: "../../img/letsgol1/u1_015_a-poster.jpg", action: "🖼", answer: "It is an a poster.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CRAYON", hint: "a crayon", emoji: "🖼", img: "../../img/letsgol1/u1_016_a-crayon.jpg", action: "🖼", answer: "It is an a crayon.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TAKE OUT YOUR BOOK", hint: "take out your book", emoji: "🖼", img: "../../img/letsgol1/u1_017_take-out-your-book.jpg", action: "🖼", answer: "It is a take out your book.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "OPEN YOUR BOOK", hint: "open your book", emoji: "🖼", img: "../../img/letsgol1/u1_018_open-your-book.jpg", action: "🖼", answer: "It is an open your book.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CLOSE YOUR BOOK", hint: "close your book", emoji: "🖼", img: "../../img/letsgol1/u1_019_close-your-book.jpg", action: "🖼", answer: "It is a close your book.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PUT AWAY YOUR BOOK", hint: "put away your book", emoji: "🖼", img: "../../img/letsgol1/u1_020_put-away-your-book.jpg", action: "🖼", answer: "It is a put away your book.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BIRD", hint: "bird", emoji: "🖼", img: "../../img/letsgol1/u1_021_bird.jpg", action: "🖼", answer: "It is a bird.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BALL", hint: "ball", emoji: "🖼", img: "../../img/letsgol1/u1_022_ball.jpg", action: "🖼", answer: "It is a ball.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BOY", hint: "boy", emoji: "🖼", img: "../../img/letsgol1/u1_023_boy.jpg", action: "🖼", answer: "It is a boy.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PEACH", hint: "peach", emoji: "🖼", img: "../../img/letsgol1/u1_024_peach.jpg", action: "🖼", answer: "It is a peach.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PENCIL", hint: "pencil", emoji: "🖼", img: "../../img/letsgol1/u1_025_pencil.jpg", action: "🖼", answer: "It is a pencil.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PINK", hint: "pink", emoji: "🖼", img: "../../img/letsgol1/u1_026_pink.jpg", action: "🖼", answer: "It is a pink.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },

  // Unit 2
  { word: "YELLOW", hint: "yellow", emoji: "🖼", img: "../../img/letsgol1/u2_027_yellow.jpg", action: "🖼", answer: "It is a yellow.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BLUE", hint: "blue", emoji: "🖼", img: "../../img/letsgol1/u2_028_blue.jpg", action: "🖼", answer: "It is a blue.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "RED", hint: "red", emoji: "🖼", img: "../../img/letsgol1/u2_029_red.jpg", action: "🖼", answer: "It is a red.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "GREEN", hint: "green", emoji: "🖼", img: "../../img/letsgol1/u2_030_green.jpg", action: "🖼", answer: "It is a green.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PURPLE", hint: "purple", emoji: "🖼", img: "../../img/letsgol1/u2_031_purple.jpg", action: "🖼", answer: "It is a purple.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "ORANGE", hint: "orange", emoji: "🖼", img: "../../img/letsgol1/u2_032_orange.jpg", action: "🖼", answer: "It is an orange.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BROWN", hint: "brown", emoji: "🖼", img: "../../img/letsgol1/u2_033_brown.jpg", action: "🖼", answer: "It is a brown.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PINK", hint: "pink", emoji: "🖼", img: "../../img/letsgol1/u2_034_pink.jpg", action: "🖼", answer: "It is a pink.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BLACK", hint: "black", emoji: "🖼", img: "../../img/letsgol1/u2_035_black.jpg", action: "🖼", answer: "It is a black.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "WHITE", hint: "white", emoji: "🖼", img: "../../img/letsgol1/u2_036_white.jpg", action: "🖼", answer: "It is a white.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TRIANGLE", hint: "a triangle", emoji: "🖼", img: "../../img/letsgol1/u2_037_a-triangle.jpg", action: "🖼", answer: "It is an a triangle.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "SQUARE", hint: "a square", emoji: "🖼", img: "../../img/letsgol1/u2_038_a-square.jpg", action: "🖼", answer: "It is an a square.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CIRCLE", hint: "a circle", emoji: "🖼", img: "../../img/letsgol1/u2_039_a-circle.jpg", action: "🖼", answer: "It is an a circle.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "STAR", hint: "a star", emoji: "🖼", img: "../../img/letsgol1/u2_040_a-star.jpg", action: "🖼", answer: "It is an a star.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DIAMOND", hint: "a diamond", emoji: "🖼", img: "../../img/letsgol1/u2_041_a-diamond.jpg", action: "🖼", answer: "It is an a diamond.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "HEART", hint: "a heart", emoji: "🖼", img: "../../img/letsgol1/u2_042_a-heart.jpg", action: "🖼", answer: "It is an a heart.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "OVAL", hint: "an oval", emoji: "🖼", img: "../../img/letsgol1/u2_043_an-oval.jpg", action: "🖼", answer: "It is an an oval.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "RECTANGLE", hint: "a rectangle", emoji: "🖼", img: "../../img/letsgol1/u2_044_a-rectangle.jpg", action: "🖼", answer: "It is an a rectangle.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PICK UP YOUR PENCIL", hint: "pick up your pencil", emoji: "🖼", img: "../../img/letsgol1/u2_045_pick-up-your-pencil.jpg", action: "🖼", answer: "It is a pick up your pencil.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DRAW A TRIANGLE", hint: "draw a triangle", emoji: "🖼", img: "../../img/letsgol1/u2_046_draw-a-triangle.jpg", action: "🖼", answer: "It is a draw a triangle.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PICK UP A", hint: "pick up a", emoji: "🖼", img: "../../img/letsgol1/u2_047_pick-up-a.jpg", action: "🖼", answer: "It is a pick up a.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DRAW A PICTURE", hint: "draw a picture", emoji: "🖼", img: "../../img/letsgol1/u2_048_draw-a-picture.jpg", action: "🖼", answer: "It is a draw a picture.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CAT", hint: "cat", emoji: "🖼", img: "../../img/letsgol1/u2_049_cat.jpg", action: "🖼", answer: "It is a cat.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COAT", hint: "coat", emoji: "🖼", img: "../../img/letsgol1/u2_050_coat.jpg", action: "🖼", answer: "It is a coat.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COW", hint: "cow", emoji: "🖼", img: "../../img/letsgol1/u2_051_cow.jpg", action: "🖼", answer: "It is a cow.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "GIRL", hint: "girl", emoji: "🖼", img: "../../img/letsgol1/u2_052_girl.jpg", action: "🖼", answer: "It is a girl.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "GATE", hint: "gate", emoji: "🖼", img: "../../img/letsgol1/u2_053_gate.jpg", action: "🖼", answer: "It is a gate.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "GOAT", hint: "goat", emoji: "🖼", img: "../../img/letsgol1/u2_054_goat.jpg", action: "🖼", answer: "It is a goat.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },

  // Unit 3
  { word: "CRAYON", hint: "a crayon", emoji: "🖼", img: "../../img/letsgol1/u3_055_a-crayon.jpg", action: "🖼", answer: "It is an a crayon.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "MARKER", hint: "a marker", emoji: "🖼", img: "../../img/letsgol1/u3_056_a-marker.jpg", action: "🖼", answer: "It is an a marker.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "NOTEBOOK", hint: "a notebook", emoji: "🖼", img: "../../img/letsgol1/u3_057_a-notebook.jpg", action: "🖼", answer: "It is an a notebook.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PENCIL CASE", hint: "a pencil case", emoji: "🖼", img: "../../img/letsgol1/u3_058_a-pencil-case.jpg", action: "🖼", answer: "It is an a pencil case.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CRAYONS", hint: "crayons", emoji: "🖼", img: "../../img/letsgol1/u3_059_crayons.jpg", action: "🖼", answer: "It is a crayons.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "MARKERS", hint: "markers", emoji: "🖼", img: "../../img/letsgol1/u3_060_markers.jpg", action: "🖼", answer: "It is a markers.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "NOTEBOOKS", hint: "notebooks", emoji: "🖼", img: "../../img/letsgol1/u3_061_notebooks.jpg", action: "🖼", answer: "It is a notebooks.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PENCIL CASES", hint: "pencil cases", emoji: "🖼", img: "../../img/letsgol1/u3_062_pencil-cases.jpg", action: "🖼", answer: "It is a pencil cases.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CD", hint: "a cd", emoji: "🖼", img: "../../img/letsgol1/u3_063_a-cd.jpg", action: "🖼", answer: "It is an a cd.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "VIDEO GAME", hint: "a video game", emoji: "🖼", img: "../../img/letsgol1/u3_064_a-video-game.jpg", action: "🖼", answer: "It is an a video game.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CELL PHONE", hint: "a cell phone", emoji: "🖼", img: "../../img/letsgol1/u3_065_a-cell-phone.jpg", action: "🖼", answer: "It is an a cell phone.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COMPUTER", hint: "a computer", emoji: "🖼", img: "../../img/letsgol1/u3_066_a-computer.jpg", action: "🖼", answer: "It is an a computer.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CDS", hint: "cds", emoji: "🖼", img: "../../img/letsgol1/u3_067_cds.jpg", action: "🖼", answer: "It is a cds.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "VIDEO GAMES", hint: "video games", emoji: "🖼", img: "../../img/letsgol1/u3_068_video-games.jpg", action: "🖼", answer: "It is a video games.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CELL PHONES", hint: "cell phones", emoji: "🖼", img: "../../img/letsgol1/u3_069_cell-phones.jpg", action: "🖼", answer: "It is a cell phones.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COMPUTERS", hint: "computers", emoji: "🖼", img: "../../img/letsgol1/u3_070_computers.jpg", action: "🖼", answer: "It is a computers.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "POINT TO", hint: "point to", emoji: "🖼", img: "../../img/letsgol1/u3_071_point-to.jpg", action: "🖼", answer: "It is a point to.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "FIND THE", hint: "find the", emoji: "🖼", img: "../../img/letsgol1/u3_072_find-the.jpg", action: "🖼", answer: "It is a find the.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COUNT THE", hint: "count the", emoji: "🖼", img: "../../img/letsgol1/u3_073_count-the.jpg", action: "🖼", answer: "It is a count the.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COUNT THE BOOKS", hint: "count the books", emoji: "🖼", img: "../../img/letsgol1/u3_074_count-the-books.jpg", action: "🖼", answer: "It is a count the books.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DESK", hint: "desk", emoji: "🖼", img: "../../img/letsgol1/u3_075_desk.jpg", action: "🖼", answer: "It is a desk.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DUCK", hint: "duck", emoji: "🖼", img: "../../img/letsgol1/u3_076_duck.jpg", action: "🖼", answer: "It is a duck.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "DOOR", hint: "door", emoji: "🖼", img: "../../img/letsgol1/u3_077_door.jpg", action: "🖼", answer: "It is a door.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TIGER", hint: "tiger", emoji: "🖼", img: "../../img/letsgol1/u3_078_tiger.jpg", action: "🖼", answer: "It is a tiger.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TWO", hint: "two", emoji: "🖼", img: "../../img/letsgol1/u3_079_two.jpg", action: "🖼", answer: "It is a two.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TOYS", hint: "toys", emoji: "🖼", img: "../../img/letsgol1/u3_080_toys.jpg", action: "🖼", answer: "It is a toys.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },

  // Unit 4
  { word: "GRANDMOTHER", hint: "grandmother", emoji: "🖼", img: "../../img/letsgol1/u4_081_grandmother.jpg", action: "🖼", answer: "It is a grandmother.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "GRANDFATHER", hint: "grandfather", emoji: "🖼", img: "../../img/letsgol1/u4_082_grandfather.jpg", action: "🖼", answer: "It is a grandfather.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "MOTHER", hint: "mother", emoji: "🖼", img: "../../img/letsgol1/u4_083_mother.jpg", action: "🖼", answer: "It is a mother.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "FATHER", hint: "father", emoji: "🖼", img: "../../img/letsgol1/u4_084_father.jpg", action: "🖼", answer: "It is a father.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "SISTER", hint: "sister", emoji: "🖼", img: "../../img/letsgol1/u4_085_sister.jpg", action: "🖼", answer: "It is a sister.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BROTHER", hint: "brother", emoji: "🖼", img: "../../img/letsgol1/u4_086_brother.jpg", action: "🖼", answer: "It is a brother.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BABY SISTER", hint: "baby sister", emoji: "🖼", img: "../../img/letsgol1/u4_087_baby-sister.jpg", action: "🖼", answer: "It is a baby sister.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BABY BROTHER", hint: "baby brother", emoji: "🖼", img: "../../img/letsgol1/u4_088_baby-brother.jpg", action: "🖼", answer: "It is a baby brother.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "TALL", hint: "tall", emoji: "🖼", img: "../../img/letsgol1/u4_089_tall.jpg", action: "🖼", answer: "It is a tall.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "SHORT", hint: "short", emoji: "🖼", img: "../../img/letsgol1/u4_090_short.jpg", action: "🖼", answer: "It is a short.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "YOUNG", hint: "young", emoji: "🖼", img: "../../img/letsgol1/u4_091_young.jpg", action: "🖼", answer: "It is a young.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "OLD", hint: "old", emoji: "🖼", img: "../../img/letsgol1/u4_092_old.jpg", action: "🖼", answer: "It is an old.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "PRETTY", hint: "pretty", emoji: "🖼", img: "../../img/letsgol1/u4_093_pretty.jpg", action: "🖼", answer: "It is a pretty.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "HANDSOME", hint: "handsome", emoji: "🖼", img: "../../img/letsgol1/u4_094_handsome.jpg", action: "🖼", answer: "It is a handsome.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "SAY THE ALPHABET", hint: "say the alphabet", emoji: "🖼", img: "../../img/letsgol1/u4_095_say-the-alphabet.jpg", action: "🖼", answer: "It is a say the alphabet.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "COUNT TO TEN", hint: "count to ten", emoji: "🖼", img: "../../img/letsgol1/u4_096_count-to-ten.jpg", action: "🖼", answer: "It is a count to ten.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "READ A BOOK", hint: "read a book", emoji: "🖼", img: "../../img/letsgol1/u4_097_read-a-book.jpg", action: "🖼", answer: "It is a read a book.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "WRITE THE WORD", hint: "write the word", emoji: "🖼", img: "../../img/letsgol1/u4_098_write-the-word.jpg", action: "🖼", answer: "It is a write the word.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "APPLE", hint: "apple", emoji: "🖼", img: "../../img/letsgol1/u4_099_apple.jpg", action: "🖼", answer: "It is an apple.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CAT", hint: "cat", emoji: "🖼", img: "../../img/letsgol1/u4_100_cat.jpg", action: "🖼", answer: "It is a cat.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "CAP", hint: "cap", emoji: "🖼", img: "../../img/letsgol1/u4_101_cap.jpg", action: "🖼", answer: "It is a cap.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
  { word: "BAG", hint: "bag", emoji: "🖼", img: "../../img/letsgol1/u4_102_bag.jpg", action: "🖼", answer: "It is a bag.", distractors: ["It is on the desk.", "I can see it.", "It is in the bag."] },
];